[wook] step15-1 리뷰 부탁드립니다!
code-squad/javascript-amazon pull request #103
Opened 2019-07-26 06:17 UTC by dxvinci

이벤트 리스너를 컨트롤러에 두었습니다. 역시나 컨트롤러는 복잡해졌습니다만 
model , view는 상대적으로 깔끔한것같습니다.

컨트롤러에서 반복이 발생하는 부분이 있습니다만 이것을 함수로 분리하기는 살짝 애매한것같습니다.
예를 들어 index를 바꾸고, render를 하고, css효과를 주는 함수들을 실행하는것인데요. 
단순 반복을 방지하기위해 
여러 함수를 실행하는 하나의 함수를 만드는것이 그렇게 좋은 방법인지 모르겠어 일단 두었습니다. 

데모 링크는 바로 댓글로 추가하도록 하겠습니다. 감사합니다 🙇‍♂️

2019-07-30 02:02 UTC, crongro requested changes
리뷰가 좀 늦었네요;

module을 잘 나눠서 개발했지만,  수정할 게 좀 보여요!

2019-07-30 02:02 UTC, crongro commented on Search/SearchModel.js
> +    const dataURL = `https://h3rb9c0ugl.execute-api.ap-northeast-2.amazonaws.com/develop/amazon_autocomplete?query=${input}`;
이런 URL은 개발서버/리얼서버마다 다른게 일반적이니 searchModel.js 밖에서 선언하는 게 좋죠.

2019-07-30 02:02 UTC, crongro commented on Search/SearchModel.js
> +    if(fetchedData.statusCode === 404) return; //데이터가 없을때 예외처리
try - catch 를 써서 async 에서 생기는 오류를 처리해보세요.

2019-07-30 02:02 UTC, crongro commented on Search/SearchController.js
> +  inputViewKeyDownHandler(e) {
몇 개 문제가 있죠.  개선하면 더 좋을거 같아요.
- 너무 크다.
- if안에 if문이 존재한다
- arrowdown/arrowup 간에 중복이 보인다.
- arrowdown/arrowup 안의 코드를 하위함수로 분리하는 게 좋겠다.(위에 중복도 같이 해결하면서)

2019-07-30 02:02 UTC, crongro commented on Search/SearchController.js
> +      const fetchedValue = e.target.innerText;
몇번 강조한 destructuring을 잘 활용해서 표현을 간결하게 해보세요.

2019-07-30 02:02 UTC, crongro commented on Search/SearchController.js
> +  registerEvents() {
이부분의 이벤트리스너를 모두 분리해서 선언하면  
'어떤 이벤트를 등록하는지'를 쉽게 알 수 있을 거 같아요.

2019-07-30 02:02 UTC, crongro commented on Search/SearchModel.js
> +  async find(input) {
find보다는 결국 get하는거니까, getData라고 하는 식이  더 낫죠.

2019-07-30 02:02 UTC, crongro commented on Search/sleep.js
> +export default function sleep(ms) {
sleep.js 하나를 덩그러니 별도 파일로 두지 말고, util이나 library 와 같은 파일을 만들고 추가하는 게 좋겠죠.

2019-07-30 02:02 UTC, crongro commented on Search/InputView.js
> +    this.div.value = value;
div 가 아닌거 같은데, input태그 아닌가요?

2019-07-30 02:02 UTC, nigayo commented on Search/HistoryView.js
> +    historys = historys.slice(0, 5); //  immutable 연습하기 splice나 spread operator를 이용해서 만들 수 있지만 이렇게 해도 되지않나?
새로운 배열을 만드는 것이면 immutable 맞겠죠.
생각한 것처럼, immutable 방식은 다양할 수 있어요.

2019-07-30 02:02 UTC, nigayo commented on Search/HistoryView.js
> +    if (this.liTemplates) {
if(!this.liTemplates) return;

2019-07-31 08:35 UTC, dxvinci commented on Search/sleep.js
> +export default function sleep(ms) {
sleep 함수는 util로 만들기에 함수가 하나밖에 없는것같아서.. 의도적으로 만들지 않았는데요 ㅎㅎ... 그래도 만드는게 좋을까요? ㅎㅎ

2019-08-02 08:12 UTC, crongro approved these changes
리팩토링을 이정도 수준으로만 해도 좋은거 같아요.
잘 수정했어요.

2019-08-02 08:12 UTC, nigayo commented on Search/InputView.js
> +    this.btn.addEventListener("click", e => {
arrow function을 썼지만 어디는 한줄 어디는 세줄.. 맞추면 더 이쁠 듯

2019-08-02 08:12 UTC, nigayo commented on Search/SearchController.js
> +    this.matchedView.curserIndex = -1;
별건 아니지만 this.matchedView.setCurserIndex(-1);
이렇게 메서드를 통해서 접근하는게 더 명시적인 방법이죠.
속성을 직접 접근하는 건 좋지 않아요. 
메서드가 일종의 인터페이스라고 생각하세요.

2019-08-02 08:12 UTC, merged