[Michelle] Step16 리뷰 부탁드립니다.
code-squad/javascript-amazon pull request #110
Opened 2019-08-08 05:26 UTC by leehwarang

### 1. 기능 구현
- 미션: **검색자동완성 API서버 만들기**
    - HTML/CSS/JS코드가 모두 Express기반에서 동작하도록 변경 -> express-generator 이용
    - 자동완성의 검색어에 대해서 fetch 요청에 응답할 수 있는 라우팅 처리

### 2. 미션을 진행 하면서 느낀 점  
- **API** 라는 말을 많이 들어봤지만 추상적으로 느껴져서 약간의 두려움(?)을 가지고 있었는데, 직접 만들어보니 "가지고 있는 데이터를 기반으로 이런 요청이 들어왔을 때 이렇게 응답해야지~" 라는 정의에 불과한 것 같아서 이제야 조금 익숙해진 것 같습니다.
- 이전에는 컴포넌트 기반으로 분리해서 하나의 폴더(ex. CarouselUI, SearchUI) 안에 css, javascript 파일이 같이 들어가 있었습니다. **express 폴더 구조에 맞게 변경**하다보니 js는 public/javascripts에, css는 public/stylesheets에 넣어야 해서 컴포넌트 분리가 흐트러졌습니다. 어떤 구조가 더 좋을지 몰라 일단 express 기준으로 맞추었습니다.

### 3. 검색 자동 완성시 가능한 문자
- iphone
- bicycle
- javascript 

### 4. 데모링크
-  https://michelle-amazon.herokuapp.com/

2019-08-16 01:32 UTC, nigayo commented
버그 : 자동완성결과를 방향키로 이동시, 한번 이후에는 계속 반복적으로 이동이 안됩니다.

2019-08-16 01:34 UTC, nigayo commented
API는 쓰임에 따라서 광범위한 내용인거 같아요. 
마지막 단어에서의 Interface라는 것이 핵심이라고 생각해요.

2019-08-16 01:36 UTC, nigayo commented
프로젝트 디렉토리 구조는 규모가 작을때, 규모가 점점 커질때, 사용하는 프레임워크에 
따라서 최선의 방법을 찾아나가야 하는 거 같아요.

요즘은 React를 하면서는 또 생각이 달라졌을 것 같은데요.

정답은 없죠.  
그때그때의 상황에 어떤 형태가 제일 좋을지 고민하는게 어떨까 합니다.

2019-08-16 01:47 UTC, crongro requested changes
서버환경셋팅과 배포까지 잘했네요.

버그없도록 구현하면 더 좋겠어요.
/node_modules는 git에 포함하지 않습니다. 왜 그래야 하는지 생각해보세요.
NodeJS에서도 ES6이상의 문법을 사용하는게 좋겠죠.
routes 파일이 안보입니다.

질문 남긴 내용 참고해서 대답도 부탁해요.

2019-08-16 01:47 UTC, nigayo commented on app.js
> +var port = process.env.PORT || 3000;
Node에서 사용되는 버전이 지원하는 ECMAScript 버전이 무엇인지 알아볼필요가 있죠.
그런점에서 var키워드는 식상해보입니다.

2019-08-16 01:47 UTC, nigayo commented on app.js
> +app.use(express.static(path.join(__dirname, "public")));
use로 뭔가 계속 등록을 하는 형태가 전부같아보이죠.

Express의 use메서드의 동작에 대해서 공부하는 것이 중요한거 같아요. (middleware개념 포함해서요)

2019-08-16 01:47 UTC, nigayo commented on app.js
> +  next(createError(404));
next메서드의 역할은 무엇일까요?

2019-08-16 01:47 UTC, nigayo commented on bin/www
> +var port = normalizePort(process.env.PORT || '3000');
process.env.PORT 이값은 어디에 있는 값일까요?

2019-08-26 15:15 UTC, leehwarang commented on app.js
> +var port = process.env.PORT || 3000;
답변이 늦어 죄송합니다. 🙏리액트 진행 중이라 놓치고 있었네요. 이 미션도 끝까지 마무리 하도록 하겠습니다.
- 
현재 Node는 es5~es6 문법은 거의 대부분 사용 가능하고, 그 이후 es7~next 까지도 사용 가능합니다. 
express-generator 로 서버를 만들었더니 var의 남용이.. ;; 모두 수정하겠습니다!

2019-08-26 15:16 UTC, leehwarang commented on app.js
> +var port = process.env.PORT || 3000;
답변이 늦어 죄송합니다. 🙏리액트 진행 중이라 놓치고 있었네요. 이 미션도 끝까지 마무리 하도록 하겠습니다.
- 
현재 Node는 es5-es6 문법은 거의 대부분 사용 가능하고, 그 이후 es7-next 까지도 사용 가능합니다. 
express-generator 로 서버를 만들었더니 var의 남용이.. ;; 모두 수정하겠습니다!

2019-08-26 16:08 UTC, leehwarang commented on app.js
> +app.use(express.static(path.join(__dirname, "public")));
기본적으로 서버(Node)란 **요청이 왔을 때 -> 라우팅 -> 그에 알맞는 응답**을 주는 애 인데,
개발자는 해당 요청에 대한 라우팅 전에  ‘추가적인 작업’을 하기 위해 미들 웨어 함수를 사용할 수 있다고 이해하고 있습니다.

직접 만들거나 npm 모듈을 가져와 사용할 때, app.use() 로 미들웨어함수를 콜백 함수로 전달!
Node란 결국 라우팅 처리를 해주는 미들웨어의 집합체가 아닐까요 ㅎㅎ

2019-08-26 16:32 UTC, leehwarang commented on app.js
> +  next(createError(404));
해당 요청(지금 코드에서는 목적지 경로가 없어서 모든 요청)에 대한 다음 미들 웨어 함수를 실행 시키는 메서드 입니다~

다음에 실행시킬 미들 웨어 함수가 없거나,  해당 요청에 대한 응답을 보내 요청-응답 주기를 종료하고 싶을 때 next()를 호출하지 않아도 된다고 생각하는데 이 부분은 좀 더 확인해볼게요!

2019-08-28 00:37 UTC, crongro commented on app.js
> +  next(createError(404));
middleware를 깊이 있게 공부안하면, express를 모르는 것이더라고요.
node웹서버는 express를 표준처럼 많이 쓰는거 같으니, 이개념을 잘 배워두시면 도움이 됩니다.
프론트개발자가  express를 다룰일은 이래저래 자주 생겨요

2019-08-28 00:41 UTC, crongro approved these changes
node_modules를 commit 하면 안되겄죠 ~
혹시 모르면 이유를 정확히 알아두세요!

승인합니다~!

2019-08-28 00:41 UTC, crongro commented on app.js
> +app.use(express.static(path.join(__dirname, "public")));
Node란 JavaScript를 브라우저 밖에서 실행해주는 프로그램이죠. 
express의 역할중 하나가 라우팅처리겠고요. 라우팅처리는 express기능의 일부분이라고 볼 수 있고요.

미들웨어를 직접 간단하게 만들어보세요.

2019-08-28 00:41 UTC, crongro commented on bin/www
> +var http = require("http");
왜 여긴 var를 ...

2019-08-28 00:42 UTC, merged