[won] 아마존 캐러셀 HTML, CSS 구현
code-squad/javascript-amazon pull request #124
Opened 2020-02-12 09:54 UTC by sangwon21

- what
    - 아마존 슬라이더 이동을 구현했습니다.
    - 슬라이더 이동 이벤트를 등록했습니다.
    - 왼쪽 오른쪽 이동을 다르게 계산하는 알고리즘을 작성했습니다.

- how
    - ES6 Class 문법을 활용하여 UI Component를 객체로 나눴습니다.
    - ES6 Class 문법 중 상속을 활용하여 event객체가 갖는 공통의 기능을 부모 객체에 주었습니다.
    - 이동을 할 때, transitionend 이벤트를 활용하여 사용자를 속였습니다.

- why
    - 전체적으로 class를 활용하여 객체 간 관계를 설정하는 데에 집중하여 코드를 작성하고 싶었습니다. 이를 위해, 객체가 서로 의존성을 맺게 하거나, 상속을 통하여 관계를 지어줬습니다. 
    - 하지만 관계 설정을 정교하게 하지 못한 결과, event객체를 구성하면서 많은 어려움이 있었습니다. 실례로, SliderEvent의 특정 이벤트 발생 후, HeaderEvent 속 이벤트를 발생시켜야 하는데, 작성해둔 구조에서는 이벤트를 발생시키기 어려운 구조였습니다. 다른 방법으로, 우회해서 해결했지만, 어설픈 구조가 주는 어려움을 이번에 겪었습니다. 또한, 굳이 상속을 쓸 필요가 있었나라는 생각도 듭니다. 일단, 객체 간 공통 요소가 보여, 그 요소를 부모 요소로 빼는 작업을 진행했는데, 그 부모 요소의 규모가 작아서, 괜히 복잡성만 코드에 더한 게 아닐까 고민됩니다. 

- 질문 사항
    - bind를 해서 this context를 강제하는 게 과연 올바른 함수 사용법인지 궁금합니다.
    - 이벤트 전달을 고려하여 코드를 작성하다 보니, 재활용성이 많이 떨어지는 함수를 작성했습니다. 특히, HTML 구조가 바꼈을 때, 유연하게 대처할 수 있는, 이벤트 전달을 고려한 함수를 작성하기 위해서는, 어떠한 영역이 필요할까요?
    - card 객체의 sortByCategory() 매서드 호출하는 곳을 살펴보면, for문 한 번으로 대체할 수 있습니다. 대신 sortByCategory()함수는 조금 더 가독성이 좋은 것 같습니다. 이런 상황에서 어떤 선택을 해야 하는지 궁금합니다.

2020-02-13 08:00 UTC, crongro commented
> * bind를 해서 this context를 강제하는 게 과연 올바른 함수 사용법인지 궁금합니다.

네 그렇게 하라고 만든함수라서 쓰면됩니다. arrow function을 사용하면 안해도 되는 경우가 있으니 확인해보세요.

2020-02-13 08:01 UTC, crongro commented
> * 이벤트 전달을 고려하여 코드를 작성하다 보니, 재활용성이 많이 떨어지는 함수를 작성했습니다. 특히, HTML 구조가 바꼈을 때, 유연하게 대처할 수 있는, 이벤트 전달을 고려한 함수를 작성하기 위해서는, 어떠한 영역이 필요할까요?

모든 함수를 재사용을 목적으로 구현하긴 어렵죠. 너무  재사용을 목적으로 생각하지는 않아도 될거고요.
가능한 부분에서만 지금의 생각을 유지하는 수준으로 구현해도 될듯해요.

2020-02-13 08:02 UTC, crongro commented
> * card 객체의 sortByCategory() 매서드 호출하는 곳을 살펴보면, for문 한 번으로 대체할 수 있습니다. 대신 sortByCategory()함수는 조금 더 가독성이 좋은 것 같습니다. 이런 상황에서 어떤 선택을 해야 하는지 궁금합니다.

어려운 질문이고, 제 생각이 정답은 아닙니다.  
성능이 중요한  ux가 아니라면, 가독성을 우선하고, 느리다면 변경합니다.ㅎ

2020-02-13 08:49 UTC, crongro requested changes
잘게 나누다 보니 좀 복잡한 관계로 보여지기도 하네요.

전체 클래스를 시각적으로 도형을 이용해서 그려보세요.
그리고 관계를 표시해보시고요.
역할이 정확하고, 흐름이 자연스러워보이는지 스스로 점검합니다.

사실 이정도 slide를 이렇게 잘게 나누는 건 과한 느낌이긴해요.
framework를 사용하면 그녀석이 담당해주는 부분이 많아서 위임할 수 있지만요.

어쨌든 좋은 시도고요! 

더 리팩토링할 게 있으면 시도해보세요!
PR은 request changes합니다.

2020-02-13 08:49 UTC, crongro commented on button.js
> +        return `${buttons}`;
reduce 잘 구현했어요.
buttonData보다는 buttons 라고 하는것도 좋을 듯.

2020-02-13 08:49 UTC, crongro commented on button.js
> +            (result, data, index) =>
index는 안쓸거면 생략 가능.

2020-02-13 08:49 UTC, crongro commented on card.js
> +class Card {
작은 컴포넌트로 나눈시도 좋아요.

2020-02-13 08:49 UTC, crongro commented on card.js
> +        return this.cardData
filter-reduce 도 좋은방법이네요.

pipeline으로 함수 composition 하는 것도 나중에 시도를!

2020-02-13 08:49 UTC, crongro commented on event-manager.js
> +class EventManager{
이것도 괜찮은 시도에요.

Event를 관장하는 녀석이 있어서 이곳에 몰아두는 것이죠. 
일종의 컨트롤러역할처럼 동작하는거죠.

2020-02-13 08:49 UTC, crongro commented on event-manager.js
> +        this.sliderEvent.addEvent($(".button2"), "click", this.sliderEvent.nextButtonListener.bind(this.sliderEvent));
bind는 이런상황에서 쓰라고 있는거니까~ 편안하게 생각하세요.
bind의 동작에 대해서 잘 이해를 하는게 오히려 중요하죠.

2020-02-13 08:49 UTC, crongro commented on slider-event.js
> +        const selectedCard = $('.selected-card');
selectedCard가 반복적으로 나오면 this로 속성으로 추가해도 될 듯.

2020-02-13 08:49 UTC, crongro commented on slider-event.js
> +    nextButtonListener(event) {
previousButtonListener 와 완전히  나누는 것도 좋은데, 
음 합칠 수 있는 방법도 있을거 같아요.

2020-02-13 08:49 UTC, crongro commented on slider-event.js
> +        if (this.isPrevious === false) {
조건문에서  === true, false 를 했는데..
엄격한 체크하는 거 아니면 if(this.isPrevious)  해도 사실 같은거라..

2020-02-13 08:49 UTC, crongro commented on slider.js
> +class Slider {
껍데기역할만 하는 slider.js 가 단순해서 좋네요.

2020-02-13 08:49 UTC, crongro commented on main.js
> +const addEvents = () => {
상속을 했으니, 장/단점을 스스로 정리해보세요.
상속이 anti-pattern만은 아닙니다!

2020-02-13 08:49 UTC, crongro commented on header-event.js
> +        if (event.target.classList.contains("header_title") === true) {
4가지조건문의 코드를 메서드로 분리해도 될 거 같네요.

2020-02-13 08:49 UTC, crongro commented on header-event.js
> +        if (event.target.classList.contains("circles") === true) {
event.target 이렇게 반복적으로 계속  찾지 말고, 변수로 담아두고 캐시해서 쓰시죠.
const {target} = event;

2020-02-13 08:49 UTC, crongro commented on slider-event.js
> +        if (middle + this.halfListLength > this.listLength) {
getDistance 메서드안에 조건문에  사용한 비교문들은 뭔지 잘 알기 어렵네요.
모두 함수로 분리하는 것도 방법이긴해요.

2020-02-13 09:23 UTC, sangwon21 commented on button.js
> +            (result, data, index) =>
index를 쓰면 reduce를 쓰는 이유가 희석되나요?

2020-02-13 09:51 UTC, sangwon21 commented on slider-event.js
> +        if (this.isPrevious === false) {
가독성 측면에서 명시적으로 if 조건문 안에 true와 false를 적었는데, true와 false를 생략하는 방법이 더 가독성이 좋을까요?

2020-02-13 09:56 UTC, sangwon21 commented on slider-event.js
> +    nextButtonListener(event) {
previousButtonListener와 nextButtonListener 각각 서로 다른 2개의 버튼에 이벤트를 달고 있습니다. 만약 합치게 되면 2개의 다른 버튼에 똑같은 함수를 Listener로 등록하게 됩니다. 비슷한 로직의 Listener들을 하나의 함수에서 처리하게 되면 복잡도가 증가하게 될 것 같습니다. 복잡도를 증가시키지 않으면서 함수를 하나로 뺄 수 있는 방법이 있을까요?

2020-02-13 10:14 UTC, sangwon21 commented on main.js
> +const addEvents = () => {
댓글에 간단히 상속을 정리해봅니다.

## 장점과 단점

- 장점
    - 상위 클래스에서 필드 및 공통 메서드를 상속하여 사용할 수 있다. 따라서 하위클래스에서 소스코드의 양이 줄어들고 기능을 확장하기 용이하다.
- 단점
    - 상속 구조가 복잡해지면 상위클래스의 변화가 하위클래스에 주는 영향을 예측하기 힘들다. 적절하지 못한 상속을 사용하면 의도했던 것과 다르게 동작할 수 있다. 
- [출처](https://defacto-standard.tistory.com/157)

### 더 읽어볼 자료
- [5 Reasons to Prefer Composition over Inheritance in Java](https://javarevisited.blogspot.com/2013/06/why-favor-composition-over-inheritance-java-oops-design.html#ixzz6DpNlDGAM)

2020-02-13 10:30 UTC, sangwon21 commented
![diagram](https://user-images.githubusercontent.com/47213425/74425482-19512d00-4e97-11ea-86dd-7032a6a11d4c.jpg)
- 말씀하신대로 적어보니 상속을 굳이 하지 않고, EventManager가 MyEvent 역할을 대신할 수 있을 것 같습니다.

2020-02-14 01:50 UTC, crongro approved these changes
좋네요.
리팩토링은  설계를 통해서 점검해보는 게  좋은거 같더라고요.
그런 재미를 느껴보면서 계속 코드를 다듬어보세요.
(코드를 너무 사랑하지는 말기 ㅎ)

2020-02-14 01:50 UTC, merged