[미션] Fetch_Amazon Carousel
code-squad/javascript-amazon pull request #140
Opened 2020-02-19 13:59 UTC by Hu2y

### 이전 피드백 완료사항
 - 의존되는 객체 주입
 - 동사목적어로 함수의 행위를 드러나게 함수명 변경
 - 매직넘버 삭제

### 미션 완료사항
 - 필요한 데이터를 JSON형태로 만들기
 - 로컬서버 환경을 구성(koa)
 - carousel.html 루트경로에 접속하게되면, fetch API 로 서버에 렌더링 될 데이터 요청 후 응답 데이터 화면에 업데이트

### 추가로 할 사항 
- 한번 가져온 데이터는 local storage에 cache해서 재사용(localstroage.setItem())
- template라이브러리  활용해보기
- instanceof() 활용, 인터페이스 만들어서 외부 데이터 요청 예외처리 해보기
- mongoDB 사용해서 데이터 가져와보기(model 추가)
- Promise, async await 적용해보기

2020-02-19 14:07 UTC, Hu2y commented
[Promise 정리 Link](https://hackmd.io/fAtlaa9KQ_WHg0daQNjDhg)

2020-02-20 05:18 UTC, crongro commented
@Hu2y  master로 PR을 보내시면 안됩니다~

2020-02-20 05:46 UTC, crongro requested changes
네이밍 위주로 조금 수정하셔야 할 듯~
MVC도전은 좋고요.

2020-02-20 05:46 UTC, crongro commented on carousel.html
> +  <script src="./main.js" type="module"></script>
utils.js 도 모듈로 관리할 수 있을 듯.

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +class Event {
Event 보다는 구체적인 이름을 짓지 그래요.
CarouselEvent !?

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +    this.menuAddEvnet(this.menuBtn)
menuAddEvnet 는 동사+명사 구조도 아니네요.

3가지가 이벤트 등록하는 것이면 3개를 묶어서 함수에서 처리하도록 하는게 어때요? 
this.cloneEl()
this.settingCss(1)
this.onEvents();

라던가.

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +    this.settingCss(1)
코드에서 1이 의미하는 것이 무엇인지 모르겠어요.
의도를 드러내주세요.

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +    this.contentArea.insertBefore(lastClone, this.contentArea.firstElementChild).classList.add('cloned')
앞서 선언한 'firstChild' 와 
여기서의 this.contentArea.firstElementChild 는 다른건가요?
변수를 재사용하지 않은거 같아요.

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +    this.contentArea.style.width = offsetWidth+'px'
여러개의 css 속성을 추가해주는 css 라는 함수를 한번 만들어볼래요?

css({
  width : offesetWidth,
  marginLeft : value
})

이런식으로~

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +    el.forEach((el, index) => {
el은 복수개인데, forEach의 el은 단수고..
이름을 다시 지어야 할 듯.

같은 이름을 쓴 것도 헷갈려보이고요.

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +    if(this.isTransition) return
JS구현시 semicolon 을 생략하는게 좋은지 온라인에서 사람들의 의견을 좀 찾아보세요.

2020-02-20 05:46 UTC, crongro commented on controller/carouselEvent.js
> +  setContentArea(index) {
이 근처에 있는 함수 네이밍은 좋네요.

2020-02-20 05:46 UTC, crongro commented on controller/controller.js
> +      "button" : new Button(renderData.buttonData)
객체를 값으로 가지고 있는 key 이름이 너무 html element를 가리키는 거 같은데요.

2020-02-20 05:46 UTC, crongro commented on controller/controller.js
> +    fetch('http://127.0.0.1:4000')
URL 하드코딩도 매직넘버라 제외해주셔야~

2020-02-20 05:46 UTC, crongro commented on controller/controller.js
> +  eventload() {
loadEvents 가 더 낫고, 궂이 이 한줄을 함수로 만들어야 할 필요성은 적어보여요.

2020-02-20 05:46 UTC, crongro commented on controller/controller.js
> +class Controller {
controller의 역할은 무엇인가요? 댓글로 설명좀 부탁드려요.

2020-02-20 05:46 UTC, crongro commented on view/carouselView.js
> +class Content {
여러개 view클래스를 나눈건 좋고요. 
파일을 여러개로 나눠도 좋을거 같아요.

2020-02-20 05:46 UTC, crongro commented on view/carouselView.js
> +    const modify = this.items.reduce((item, data) => {
reduce의 반환타입이 무엇이죠? modify가 그 타입을 의미하는 이름이면 더 좋겠어요.

2020-02-21 12:40 UTC, Hu2y commented on carousel.html
> +  <script src="./main.js" type="module"></script>
webpack 공부해 보면서 css, js 파일 번들링해서 코드에 적용해보겠습니다.

2020-02-21 12:41 UTC, Hu2y commented on controller/carouselEvent.js
> +class Event {
네이밍 ㅜㅜ 신경쓰도록 하겠습니다.

2020-02-21 12:44 UTC, Hu2y commented on controller/carouselEvent.js
> +    this.menuAddEvnet(this.menuBtn)
이벤트를 등록해주는 부분, 함수로 묶어서 처리하도록 하겠습니다.

2020-02-21 12:45 UTC, Hu2y commented on controller/carouselEvent.js
> +    this.settingCss(1)
첫 인덱스를 나타내는 의미여서 상수로 변수 등록해서 사용하겠습니다.

2020-02-21 12:47 UTC, Hu2y commented on controller/carouselEvent.js
> +    this.contentArea.insertBefore(lastClone, this.contentArea.firstElementChild).classList.add('cloned')
같은 element여서 재사용 하겠습니다.

2020-02-21 12:53 UTC, Hu2y commented on controller/carouselEvent.js
> +    if(this.isTransition) return
Prettier를 설정하여 코드에서 세미콜론을 자동으로 제거하도록 사용하고 있었는데, 
```javascript
const a = 1
const b = 2
const c = a + b
(a + b).toString()

//VM145:3 Uncaught TypeError: b is not a function
```
간단한 코드도 에러 발생되는 부분도있어.. 붙이는 습관을 가지겠습니다.

2020-02-21 12:54 UTC, Hu2y commented on controller/controller.js
> +    fetch('http://127.0.0.1:4000')
넵, 상수로 변수 등록해서 사용하겠습니다.

2020-02-21 12:54 UTC, Hu2y commented on controller/controller.js
> +  eventload() {
불필요한 코드 삭제하겠습니다.

2020-02-21 13:41 UTC, Hu2y commented on controller/controller.js
> +class Controller {
모델(데이터를 받아오는곳, 지금은 목데이터..)과 view(화면을 만들어주는 영역) 사이, 중간에서 데이터를 전달해주고, 모든 로직을 담당하도록 의도하고 만들었는데.. 의도한대로 잘 되었는지 모르겠습니다.

2020-02-24 05:34 UTC, crongro approved these changes
웹팩환경이 추가됐군요 ~! 
코드 수정이 잘 된거 같네요.
수고하셨어요.

2020-02-24 05:34 UTC, crongro commented on controller/controller.js
> +      fetch('http://127.0.0.1:4000')
URL을 fetchData의 인자로 받으면 더 좋았을 듯.

2020-02-24 05:34 UTC, crongro commented on controller/controller.js
> +        .then(responseData => {
response너무 길어서 res라고만 작성해도, 개발자들은 서로 다  아는거 같아요.

2020-02-24 05:34 UTC, crongro commented on package.json
> +  "devDependencies": {
오우 웹팩~!

2020-02-24 05:34 UTC, crongro commented on webpack.config.js
> +module.exports = {
웹팩환경을 잘 이해하면서 빌드해보세요!

2020-02-24 05:34 UTC, merged