Fetch API를 이용한 데이터 처리
code-squad/javascript-amazon pull request #141
Opened 2020-02-19 15:00 UTC by sangwon21

- what
  - 데이터를 비동기적으로 불러오는 작업을 진행했습니다.
  - Promise, async와 await을 활용하여 비동기를 제어했습니다.
  - webpack을 활용하여 js파일과 css 파일을 번들링했습니다.
  - 서버 환경(express)을 구축했습니다.

- how
  - fetch API를 통해, 서버에 데이터를 요청한 이후, 받아온 데이터를 다뤘습니다.
  - 받아온 데이터를 class의 변수로 캐싱했습니다. 
  - webpack.config.js 파일을 통해, webpack을 번들링하는 과정에서 필요한 설정을 미리 정했습니다.
  - express-generator를 활용해, 미리 정해진 규격대로 express서버를 구축했습니다. 

- why
  - fetch API를 통해 비동기적으로 데이터 요청을 처리할 수 있었습니다. 
  - webpack을 통해 css와 js를 하나의 component로 묶울 수 있어서 UI component 의미가 강화되었습니다.

- 더 해야될 일
  - promise와 async, await을 조금 더 이해하기
  - 슬라이더 동작 개선

2020-02-20 05:48 UTC, crongro commented
커멋단위, 커밋로그 좋아요 💯

2020-02-20 05:49 UTC, crongro commented
dist아래에  빌드된 파일은 소스코드에 올리지 않긴해요~

2020-02-20 06:26 UTC, crongro requested changes
수고했네요.

리뷰 남긴 내용 수정해보세요~

2020-02-20 06:26 UTC, crongro commented on client/src/button.js
> +class Button {
디렉토리 이름을
client/src/view/button.js 라고 하면 더 좋을 듯.

2020-02-20 06:26 UTC, crongro commented on client/src/card.css
> +.card-wrapper {
sass 익숙한가요? 써보세요.

2020-02-20 06:26 UTC, crongro commented on client/src/card.js
> +        this.idIndex = 1;
id보다는 cardIndex 라고 해도 될 듯. (카드 맞으면)

2020-02-20 06:26 UTC, crongro commented on client/src/card.js
> +            .reduce((result, data) => (result += `<li class="card ${this.idIndex === 1 ? "selected-card" : ""}" id=card-${this.idIndex++}><div class="card-copy"><span class="card-category ${data.cate
HTML문자열이 가로로 길어서 보기 어렵네요. 개행해도 잘 될거에요

2020-02-20 06:26 UTC, crongro commented on client/src/card.js
> +        const moreList = this.sortByCategory("more");
this.sortByCategories(["ship", "stream", "shop", "read", "more"]);
이렇게 동작해서 중복코드를 줄이면 좋을 듯.

2020-02-20 06:26 UTC, crongro commented on client/src/constants.js
> +    SERVER: "http://localhost:8080/cards"
development 와 production 을 고려해야 할텐데요.

URL = {
 API_SERVER : {
     DEV : "",
     STAGE : "",
  }
}

이런식으로 여러가지 개발환경을 염두해서 만들면 더 좋을 듯.

2020-02-20 06:26 UTC, crongro commented on client/src/event-manager.js
> +import { $, $$ } from "./util.js";
as 앨리어스를 사용해보세요.

2020-02-20 06:26 UTC, crongro commented on client/src/event-manager.js
> +        this.sliderEvent.addEvent($(".button2"), "click", this.sliderEvent.nextButtonListener.bind(this.sliderEvent));
arrow function을 사용하면 bind를 쓰지 않아도 될 수 있다는거 알고있죠?
왜 그런지 설명할 수 있어야 함.

2020-02-20 06:26 UTC, crongro commented on client/src/header-event.js
> +class HeaderEvent extends MyEvent {
MyEvent라기 보다는 CoreEvent, CommonEvent, ParentEvent, EventManager 등의 이름이 더 나을 듯.

2020-02-20 06:26 UTC, crongro commented on client/src/header-event.js
> +        target.parentNode.querySelector(".dot").classList.add("selected-dot");
const dotNode =  target.parentNode.querySelector(".dot")

재사용하기!

2020-02-20 06:26 UTC, crongro commented on client/src/header-event.js
> +        if (target.classList.contains("header_title") === true) {
여긴 개행이 2줄도 있고 너무 넉넉하네요 ㅎ

2020-02-20 06:26 UTC, crongro commented on client/src/header.js
> +        for (let i = 0; i < length; i++) {
가급적 forEach 사용~

2020-02-20 06:26 UTC, crongro commented on client/src/main.js
> +    const eventManager = new EventManager();
여기 eventManager가 있군요.

2020-02-20 06:26 UTC, crongro commented on client/src/main.js
> +const constructHTML = async () => {
생성자의 단어와 비슷해서.. 전 별로

2020-02-20 06:26 UTC, crongro commented on client/src/slider-event.js
> +        this.listLength = 17;
default 값이라는 걸 의미하면 더 좋을 듯. 

this.defaultOption = {
        this.currentIndex :0,
        this.listLength : 17
}

2020-02-20 06:26 UTC, crongro commented on client/src/slider-event.js
> +            cardWrapper.style.transform = `translateX(${-1080 * distance}px)`;
1080 magic number! 변수화라도 시키세요.

2020-02-20 06:26 UTC, crongro commented on client/src/slider-event.js
> +        this.moveByDistance(-1);
혹시 ,
 this.moveByDistance(this.distance) 가 아닐까요?

2020-02-20 06:26 UTC, crongro commented on client/src/slider-event.js
> +        const childNodes = Array.from(cardWrapper.children);
spread opeartor 도 활용해보세요. from말고요.

2020-02-20 06:26 UTC, crongro commented on client/src/slider-event.js
> +        if (1 <= target && target <= middle + this.halfListLength - this.listLength) {
if문 안에 내용이 너무 길고 복잡해요.
변수로 저장을 먼저 하는건 어때요.

2020-02-20 06:26 UTC, crongro commented on client/src/slider-event.js
> +    getDistance(middle, target) {
getDistance 메서드지만 거리를 반환하지는 않네요.

2020-02-20 06:26 UTC, crongro commented on client/src/slider-event.js
> +    dotEventListener(event) {
dot 이 무엇의미인지 전 잘 모르겠네요.

2020-02-20 06:26 UTC, crongro commented on client/src/main.js
> +        const cardData = await slider.fetchCardData();
fetch 사용과 promise 반환을 잘 이해하신 듯.

2020-02-21 07:26 UTC, sangwon21 commented on client/src/button.js
> +class Button {
의미가 더 살아나는 방향인 것 같습니다. view로 한 번 묶어보겠습니다.

2020-02-21 07:44 UTC, sangwon21 commented on client/src/card.js
> +        this.idIndex = 1;
cardIndex가 id보다 조금 더 명확한 의미를 가지는 것 같습니다.

2020-02-21 07:53 UTC, sangwon21 commented on client/src/card.js
> +            .reduce((result, data) => (result += `<li class="card ${this.idIndex === 1 ? "selected-card" : ""}" id=card-${this.idIndex++}><div class="card-copy"><span class="card-category ${data.cate
협업하는 다른 사람의 시선을 염두에 두고 코딩을 하도록 노력하겠습니다.

2020-02-21 08:03 UTC, sangwon21 commented on client/src/card.js
> +        const moreList = this.sortByCategory("more");
코드를 작성하면서 찝찝한 부분이었는데, 좋은 해결 방향성을 제시해줘서 감사합니다.

2020-02-21 08:07 UTC, sangwon21 commented on client/src/slider-event.js
> +    getDistance(middle, target) {
get 메서드와 set메서드를 햇갈렸네요. setDistance로 바꾸겠습니다.

2020-02-21 08:10 UTC, sangwon21 commented on client/src/slider-event.js
> +    dotEventListener(event) {
dot은 헤더(상단의 작은 박스) 속 동그라미를 의미합니다. 좀 더 명징한 이름이 있을까요?

2020-02-21 08:11 UTC, sangwon21 commented on client/src/header.js
> +        for (let i = 0; i < length; i++) {
특정 숫자만큼 돌고 싶을 때, for문을 어떻게 대체할 수 있을까요?

2020-02-21 08:12 UTC, sangwon21 commented on client/src/slider-event.js
> +        this.moveByDistance(-1);
네, 말씀하신 방법대로 하면 의미가 명확해져서 그렇게 바꾸겠습니다.

2020-02-21 08:18 UTC, crongro commented on client/src/slider-event.js
> +    dotEventListener(event) {
동그라미도 뭔가 의미가 있지 않나요? 
형태를 표현하지 말고..의미를 부여하는거 가능하면 그렇게 해보시죠.

2020-02-21 08:18 UTC, crongro commented on client/src/header.js
> +        for (let i = 0; i < length; i++) {
아 가능하지만 그냥 for문이 더 낫겠네요!

2020-02-21 10:21 UTC, sangwon21 commented on client/src/constants.js
> +    SERVER: "http://localhost:8080/cards"
질문이 있습니다. node 환경에서는 process.env를 통해 production환경과 development환경을 구별할 수 있었던 것 같은데, 브라우저 환경에서는 따로 구별하는 방법이 있을까요?

2020-02-21 10:40 UTC, sangwon21 commented on client/src/slider-event.js
> +        const childNodes = Array.from(cardWrapper.children);
spread operator가 유사 배열에도 적용이 가능하군요.  [참고 자료](https://stackoverflow.com/questions/222841/most-efficient-way-to-convert-an-htmlcollection-to-an-array)

2020-02-21 10:41 UTC, sangwon21 commented on client/src/main.js
> +const constructHTML = async () => {
renderHTML로 교체(?)하겠습니다.

2020-02-21 15:10 UTC, sangwon21 commented on client/src/card.css
> +.card-wrapper {
sass 한 번도 써본 적이 없지만 해보겠습니다

2020-02-21 15:22 UTC, sangwon21 commented
## 고치거나 바꾼 부분
- 변수명이나 함수명 혹은 클래스명에 범용적이거나 일반적인 이름 대신 역할에 적확한 이름을 사용해 보려고 노력했습니다.
- 슬라이더 동작을 개선했습니다. 애니메이션 이동 거리 알고리즘이 리팩토링 과정에서 문제가 발생하여 해결했습니다. 더불어 애니메이션 진행 중에 또 다시 애니메이션 이벤트가 발생하면 카드 순서가 헝클어지는 문제가 발생했는데, 애니메이션 진행 중에는 또다른 애니메이션이 발생하지 않는 방향으로 수정했습니다.
- DOM 캐싱을 통하여 불필요한 DOM 노드 탐색을 줄였습니다.
- 함수 커링을 통하여 한층 더 가독성이 좋은 코드를 작성했습니다.

## 더 해볼 부분
- sass 사용해보기
- webpack에 유용한 loader 및 plugin 사용해보기
-  함수 커링에 대하여 공부해보기
- 서로 다른 모드(production, development 등)에서 다르게 동작하게 연구해보기

2020-02-24 05:44 UTC, crongro approved these changes
네 수정사항 확인했어요.
css preprocessor사용시도도 좋네요. 다양한 기능이 많은거 같으니  하나 둘 씩 기능을 사용해보세요.

2020-02-24 05:44 UTC, crongro commented on client/src/view/header.scss
> +    background-image: url(https://web.archive.org/web/20180717213726im_/https://images-na.ssl-images-amazon.com/images/G/01/marketing/prime/detail_page/InteractivePlane_TILES_SpriteSheet_E._CB5132853
참고로 콘텐츠의 일부라면, img태그를 사용해야 한다는 점도 기억해주세요.

2020-02-24 05:44 UTC, crongro commented on client/src/view/header.scss
> +  background-color: #ffffff;
축약표기법을 사용해보시죠.. 
#fff

2020-02-24 05:45 UTC, merged