Fetch
code-squad/javascript-amazon pull request #142
Opened 2020-02-22 04:26 UTC by Rachel4858

## javascript-amazon

### 파일설명
* server Directory
    * localData.json : 서버data
    * Server.js : 서버구현
* src Directory
    * image Directory : image files
    * style Directory : css files
    * Carousel.js : class Carousel 
    * CarouselManager.js : class CarouselManager (fetchAPI로 서버에 데이터 요청)
    * CarouselManagerWithComment.js : class CarouselManager With comment(코드들에 대해 정리 및 복습)
* promise-practice Directory : Promise객체구현, fetchAPI연습

2020-02-23 08:17 UTC, DongHyunKims reviewed
한주동안 고생 하셨습니다!

2020-02-23 08:17 UTC, DongHyunKims commented on src/CarouselManager.js
> +      console.log("!!!!!");
불필요한 console은 최대한 없애 주는 것이 좋아요!

2020-02-23 08:17 UTC, DongHyunKims commented on src/CarouselManager.js
> +      console.log('??????');
여기두요!

2020-02-23 08:17 UTC, DongHyunKims commented on src/CarouselManager.js
> +          localStorage.setItem('carouselJson', JSON.stringify(this.carouselList));
캐러셀 list를 `localstorage`에 저장하는 이유가 따로 있을까요? 전체 리스트를 패치 해오지 않는 용도로 사용한 거라면 다시 패치하고 현재 캐러셀의 위치 정도만 저장해 놓는 방법은 어떨까요?

2020-02-23 08:17 UTC, DongHyunKims commented on src/CarouselManager.js
> +      .forEach((carousel) => this.carouselWrapperElement.appendChild(new Carousel(carousel).render()));
가독성이 떨어지는 코드 같아요~! 
```
const list = [this.carouselList[this.carouselList.length - 1], ...this.carouselList, this.carouselList[0]];
list.forEach(...)
```

위 예제와 같이 변수로 할당한다면 좀 더 가독성이 좋아질 꺼에요~

2020-02-23 08:17 UTC, DongHyunKims commented on src/CarouselManager.js
> +    props.menuBtnElements.forEach((element, index) => element.addEventListener('click', this.calculateCarouselContentStyleToMenu.bind(this, index)));
이미 아시겠지만 `Event Delegation`을 통해 구현해 볼 수 있지 않을까요?

https://joshua1988.github.io/web-development/javascript/event-propagation-delegation/

2020-02-23 08:17 UTC, DongHyunKims commented on src/CarouselManager.js
> +    }
이 메소드를 만든 목적이 있을까요? 해당 엘리먼트의 인덱스로 바로 이동 시키면 되지 않을까요?

2020-02-24 05:49 UTC, crongro commented
@Rachel4858  충돌이 났네요.
Local환경에서 먼저 PULL을 받아서 충돌을 해결해보셔야 할 듯.

2020-02-24 05:50 UTC, crongro requested changes
커밋로그가 동일한 내용들이 보입니다.
매 커밋마다 의미있는 커밋 내용으로 작성해보세요.

올려주신 코드가 기존에 merged된 코드와 충돌이 난 거 같으니 이부분도 확인해보세요.

2020-02-28 01:08 UTC, crongro commented
@Rachel4858 충돌해결후 다시 push 해주시죠?

2020-03-09 09:05 UTC, closed without merging