아마존 네비게이션 UI Fetch API 적용
code-squad/javascript-amazon pull request #145
Opened 2020-02-23 08:28 UTC by reesekimm

### 지난 피드백 내용 반영
1. ES6 modules 적용
2. `classList`에 대한 polyfill 적용
    - polyfill이 제 역할을 하는지 IE에서 확인해보려고 했는데, IE는 `<script type="module">`와 `import/export`에 대한 지원이 안돼서 추가로 polyfill 작업이 필요하더라구요.. 계속 알아보긴 했는데 시간이 꽤 오래 걸리고 당장은 중요도가 떨어지는 것 같아 미뤄뒀습니다;

### 이번 미션 작업 내용
1. mediator pattern 적용
    - mediator가 slide animation을 전담하도록 해보았습니다. 원래 계획은 mediator가 상단 네비게이션이나 버튼으로부터 요청을 받으면 index를 제어해서 카드리스트에게 슬라이드 애니메이션을 '요청'하도록 만드는거였는데, 로직이 꼬여서 최종적으로는 mediator'가' 애니메이션을 구현하게 되었습니다. (이부분은 계속해서 고민해볼 부분듯 해요.)<br />
   
   - ❓ 궁금한 점
    1. `transitionend` 이벤트의 listener 내부에 `console.log(cardIdx)`를 추가하고 좌우 이동 버튼을 눌러 슬라이드를 움직이면 콘솔에 아래와 같이 인덱스가 여러 번 찍힙니다. transition이 끝나기 전인데 listener가 동작하는 이유가 무엇일까요?.. 이유를 못찾았습니다ㅠ
![log cardIdx](https://i.postimg.cc/prsZrq5T/2020-02-23-16-38-37.png)

<br />

리뷰 감사합니다! 🤩

2020-02-23 14:36 UTC, DongHyunKims reviewed
굉장히 고생 많으셨어요~ 코드의 가독성이 좋고 코드를 깔끔하게 작성하려고 노력하는게 보여 보기 좋습니다~

2020-02-23 14:36 UTC, DongHyunKims commented on components/buttons.js
> +import { $qsa, $ael } from "../util.js";
`qsa`, `ael`와 같은 변수 명은 사용하지 않는 것이 좋아요~ 특히 util성 변수에서는 더욱더요~ 다른 개발자와 협업시에 공식적인 축약형을 사용하지 않으면 많이 번거로워 지거든요~ 최대한 풀어서 사용하는것이 좋아요~

하지만 이런 util성 함수를 만들어보는 것은 아주 좋은 작업입니다~

2020-02-23 14:36 UTC, DongHyunKims commented on components/cards.js
> +      `px);">${cards}</div></div>`
가독성을 위해 모두 `tagged template literal`로 작성해보면 어떨까요?

2020-02-23 14:36 UTC, DongHyunKims commented on components/cards.js
> +    }, "");
reduce를 통해 card를 생성하는 부분이 좋아 보이네요~ 하지만 이런 부분은 코드의 가독성을 떨어뜨리기 때문에 함수로 할당해 주는 것이 어떨까요?

2020-02-23 14:36 UTC, DongHyunKims commented on slide-anim-mediator.js
> +import { $qs, $ael } from "./util.js";
`slide-anim-mediator.js` 이 파일 이름도 `anim`보단 `animation`으로 풀어 사용하는게 좋을 것 같네요~ 그리고 파일이름엔 camelcase를 많이 사용하는데 dash를 사용해서 작성한 이유가 있을까요?

2020-02-23 14:36 UTC, DongHyunKims commented on slide-anim-mediator.js
> +  const _updateState_btn = function(index) {
여기서도 camel case를 사용하는게 좋아보이네요~

2020-02-23 14:36 UTC, DongHyunKims commented on slide-anim-mediator.js
> +  };
mediator에 애니메이션 작업들을 위임하니 관리 측면에서 굉장히 편하겠네요~ 중복도 많이 피할수 있을것 같구요~ 좋은 시도로 보여요~

2020-02-23 14:36 UTC, DongHyunKims commented on server.js
> +});
`cors`에 대해 한번 정리 해보면 어떨까요? 그리고 express를 wrapping해서 서버 util을 만드는 것도 추천해볼게요~ 코드의 중복을 많이 줄일수 있고, express를 이해하는데 굉장히 도움이 많이 될거에요~

2020-02-24 01:42 UTC, reesekimm commented on components/cards.js
> +      `px);">${cards}</div></div>`
넹, `tagged template literal` 적용해보려고 합니다~!

2020-02-24 01:54 UTC, reesekimm commented on slide-anim-mediator.js
> +import { $qs, $ael } from "./util.js";
https://developers.google.com/style/filenames
파일명 컨벤션을 찾아보다가 ☝️여기 참고해서 소문자랑 하이픈(-)을 사용해서 파일명을 정했어요. 현업에서는 camelcase를 많이 쓰는걸까요?_?

2020-02-24 01:56 UTC, reesekimm commented on server.js
> +});
이번 방학때 한번 해봐야겠습니다😃 짱짱!

2020-02-24 01:59 UTC, reesekimm commented
> 굉장히 고생 많으셨어요~ 코드의 가독성이 좋고 코드를 깔끔하게 작성하려고 노력하는게 보여 보기 좋습니다~

리뷰 고맙습니다~!
오늘 말씀해주신 내용 참고해서 코드 수정해보고
추가적으로 공부도 해볼게요!

2020-02-24 02:00 UTC, reesekimm commented on server.js
> +});
> `cors`에 대해 한번 정리 해보면 어떨까요? 그리고 express를 wrapping해서 서버 util을 만드는 것도 추천해볼게요~ 코드의 중복을 많이 줄일수 있고, express를 이해하는데 굉장히 도움이 많이 될거에요~

이번 방학때 한번 해봐야겠습니다😃 짱짱!

2020-02-24 02:00 UTC, reesekimm commented on slide-anim-mediator.js
> +import { $qs, $ael } from "./util.js";
> `slide-anim-mediator.js` 이 파일 이름도 `anim`보단 `animation`으로 풀어 사용하는게 좋을 것 같네요~ 그리고 파일이름엔 camelcase를 많이 사용하는데 dash를 사용해서 작성한 이유가 있을까요?

https://developers.google.com/style/filenames
파일명 컨벤션을 찾아보다가 ☝️여기 참고해서 소문자랑 하이픈(-)을 사용해서 파일명을 정했어요. 현업에서는 camelcase를 많이 쓰는걸까요?_?

2020-02-24 02:01 UTC, reesekimm commented on components/cards.js
> +      `px);">${cards}</div></div>`
> 가독성을 위해 모두 `tagged template literal`로 작성해보면 어떨까요?

넹, tagged template literal 적용해보려고 합니다~!

2020-02-24 06:00 UTC, crongro commented
@reesekimm  pr보내신 파일이 충돌이 있네요.
로컬에서 먼저 해결하시고 보내주시면 좋겠어요!

2020-02-24 06:01 UTC, crongro commented
> `transitionend` 이벤트의 listener 내부에 `console.log(cardIdx)`를 추가하고 좌우 이동 버튼을 눌러 슬라이드를 움직이면 콘솔에 아래와 같이 인덱스가 여러 번 찍힙니다. transition이 끝나기 전인데 listener가 동작하는 이유가 무엇일까요?.. 이유를 못찾았습니다ㅠ

>
잘 모르겠네요(@.@) 
분명한 건 트랜지션 과정이 끝난 다음에 실행된다는 사실입니다. ㅎ 
다른 트랜지션 과정이 종료됐거나, 아니면 지연실행되는건 아닌지 확인을...

2020-02-24 06:03 UTC, crongro requested changes
충돌문제가 있으니 수정부탁드려요.

2020-02-24 06:21 UTC, reesekimm commented
충돌 해결 후 다시 PR 하겠습니다

2020-02-24 06:21 UTC, closed without merging