Animation
code-squad/javascript-amazon pull request #151
Opened 2020-02-24 10:18 UTC by choichoigang

mock data 기반과 모듈화를 목적으로 으로 기존 코드를 삭제하고 다시 설계

1.navdata.js 와 carousel.js 목데이터 생성
2.목데이터를 import 해서 navinner.js와 carousel.js에서 html에  element를 그려주는 작업
3.navinner.js 와 carousel.js 를 import 해서 각각 필요한 애니메이션을 navanimation.js 와 carouselanimation.js 에서 독립적으로 작업
4. main.js는 navanimation.js 와 carouselanimation.js 를 import 받아서 애니메이션을 컨트롤

미스테리 넘버들을 최대한 줄이는 작업

2020-02-25 05:06 UTC, crongro requested changes
전체적으로 함수/객체/클래스 네이밍이 엉망입니다.
수정해주세요.

2020-02-25 05:06 UTC, crongro commented on JS/CSS/style.css
> +  background-color: cadetblue;
실제 현업에서는 다양한 색표현을 위해서 16진수로 표현하긴해요.

2020-02-25 05:06 UTC, crongro commented on JS/CSS/style.css
> +  position: absolute;
button_prev 클래스와 중복코드를 묶어서 공통 클래스로 만들어서 사용해보세요.

2020-02-25 05:06 UTC, crongro commented on JS/carouselanimation.js
> +import library from "./library.js";
library는 너무 일반적인 이름이네요. 구체적으로 무엇인지 이름지어보세요.

2020-02-25 05:06 UTC, crongro commented on JS/carouselanimation.js
> +import CarouselDataControlloer from "./carouselinner.js";
파일명에도 카멜케이스를 사용해서 가독성을 올려주세요.

2020-02-25 05:06 UTC, crongro commented on JS/carouselanimation.js
> +  transform() {
setTranstion 이라고 하는게 나을듯

2020-02-25 05:06 UTC, crongro commented on JS/carouselanimation.js
> +  transformNone() {
여기에 transform 관련 속성을 지우는 건 없는 거 같은데요?  이름고 동작이 달라요~

2020-02-25 05:06 UTC, crongro commented on JS/carouselanimation.js
> +  transitionEndEvent(counter) {
onTransitionEndEvent라던가 ..
동사+명사를 지켜주세요

2020-02-25 05:06 UTC, crongro commented on JS/library.js
> +let library = {
library보다는  util 또는 (_) 등을 써도 될 듯.

2020-02-25 05:06 UTC, crongro commented on JS/carouselinner.js
> +    let firstIndex = 0;
여기서 let을 사용한 이유는 뭔가요?

2020-02-25 05:06 UTC, crongro commented on JS/main.js
> +const CarouselAnimationCall = new CarouselAnimation(carouselDom);
클래스는 보통 대문자로 시작하고, 객체는 소문자로 시작해요~

2020-02-25 05:06 UTC, crongro commented on JS/main.js
> +const navAnimationCall = new navAnimation(navItems);
클래스는 보통 대문자로 시작하고, 객체는 소문자로 시작해요~


여기도.

2020-02-25 05:06 UTC, crongro commented on JS/main.js
> +class Main {
Carousel 메인 컨트롤러 같은 그런거아닐까요?
Main 이라는 이름은 의도가 드러나지 않아요.

2020-02-25 05:06 UTC, crongro commented on JS/main.js
> +        CarouselAnimationCall.transformNone();
CarouselAnimationCall.transformNone(); 
이코드는 if/else에 동시에 같이 쓰이는 코드니까 밖으로 빼도 되긴할듯.

2020-02-25 05:06 UTC, crongro commented on JS/navanimation.js
> +      el.addEventListener("click", () => {
delegation을 적용해볼만하겠네요.

2020-02-25 05:06 UTC, crongro commented on JS/navanimation.js
> +    this.navItems[counter - 2].style.transform = "none";
2,1,3 이런숫자들은 모두 매직넘버라서..
좋지 않은 코드입니다.
다들 의미는 있을테니, 변수로 이름을 지어서 사용해보세요.

2020-02-26 06:44 UTC, choichoigang commented on JS/main.js
> +const navAnimationCall = new navAnimation(navItems);
수정하도록 하겠습니다 !

2020-02-26 06:44 UTC, choichoigang commented on JS/main.js
> +class Main {
class의 용도가 명확하게 드러내는 단어를 생각해 보겠습니다

2020-02-26 06:45 UTC, choichoigang commented on JS/main.js
> +        CarouselAnimationCall.transformNone();
애니메이션 모듈에서 컨트롤 가능하도록 설계하겠습니다.

2020-02-26 06:46 UTC, choichoigang commented on JS/navanimation.js
> +    this.navItems[counter - 2].style.transform = "none";
작동에 급급해서 의미를 부여하지 못한거 같습니다.
개선하도록 하겠습니다 !

2020-02-26 06:47 UTC, choichoigang commented on JS/CSS/style.css
> +  background-color: cadetblue;
색표현을 단어로 하는게 익숙해서 그랬는데 16진수로 표현하는 방법을 확인해서 앞으로 적용시키는 방향으로 하겠습니다 !

2020-03-09 09:06 UTC, closed without merging