Search 자동완성창 UI 작성
code-squad/javascript-amazon pull request #156
Opened 2020-02-26 05:03 UTC by sangwon21

- what
  - 검색어를 입력하면 해당 검색어로 시작하는 단어 목록이 화면에 등장하게끔 했습니다.
  - 자동완성 결과는 키보드 위/아래키로 이동할 수 있게 했습니다.
  - 노출된 데이터 중 검색어와 일치하는 단어는 색깔이 하이라이트 되여 보여지게 했습니다.
  - 검색 대상이 되는 단어들은 영문학 고전과 꼭 봐야할 영어권 영화 100선을 선정했습니다.

- how
  - 단어 목록이 화면에 렌더링 되기 위해서는 먼저, 데이터가 필요합니다. 그래서 데이터를 받아오기 위하여 서버에 fetch하는 작업을 시작했습니다.
  - 자동완성 결과를 키보드 위 아래로 움직이는 건, 키보드 이벤트를 이용하여 해당 키가 들어왔을 때, 알맞는 리스너 함수(listener)를 작성하여 해결했습니다.
  - 일치하는 단어의 색깔이 하이라이트 되는 부분은 css의 클래스를 줌으로써 해결했습니다.

- why
  - 데모를 보여주기 위해서, 로컬 서버를 이용할 수 없어, firebase를 이용하여 배포했습니다.

- 개선할 점
  - 로컬 서버를 이용해서 개발할 때, 고려하지 않았던 문제점, 응답 속도를 해결하는 방법을 찾아야 합니다.
  - 특히, 데모 주소에 처음 들어갔을 때, 검색창이 보이지 않고 새로고침을 해야만 보이는 오류가 있는데 이를 해결해야 합니다. 
  - 동작 중에 사용자 예상과 다른 움직임들이 있어 보완해야 합니다.
  - dataset을 손수 만들다 보니 비효율적이었습니다. 조금 더 자동화할 수 있는 방법을 강구해야 합니다.
- 더 공부할 점
  - firebase를 조금 더 이해해야 합니다.
  - sass를 좀 더 sass처럼 써야 합니다. 

[데모](https://sangwon21.github.io/amazon-ui/client/slider.html)

2020-02-26 09:19 UTC, crongro requested changes
리뷰남겨두고 PR은 request change 상태로 둘테니, 
개선해보세요.

잘 구현중입니다. 본인을 믿고 계속 고고!

2020-02-26 09:19 UTC, crongro commented on client/src/main.js
> +    const searchBar = new SearchBar(searchList);
main에서 같이 초기화 하는 거 좋네요.

2020-02-26 09:19 UTC, crongro commented on client/src/util/constants.js
> +    DEV: {
굿굿 
현업에서는 production mode 뿐아니라 beta mode 등 다양한 단계로 개발하죠.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/model.js
> +        const proxy = new Proxy(this, {
Proxy!!! 패턴을 구현한 셈이네요. 
객체모니터링하다가 어떤 변경을 해주는 장점이 있죠.
🥇

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +} from "../../util/constants.js";
너무 많으면 하나의 객체로 받아서 처리해도 될 듯.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +    // 참고: https://www.zerocho.com/category/JavaScript/post/59a8e9cb15ac0000182794fa
참고하는 거 좋고요. 
잘 이해해서 수정할 수 있으면 됨.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +        const targetString = event.target.value;
destructuring문법도 활용하세요.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +        if (targetString === "") {
targetString이 공백인경우에도 this.timer 체크를 해야하는건데 맞죠? 
코드 순서가 그렇게 되어 있길래 확인차 질문.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +        }.bind(this), 200);
arrow function을 쓰면 bind가 필요 없을까요? 
왜그렇죠?

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +    isArrowKeyCode(keyCode) {
이런함수 좋음.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +        const inspectionClassList = ["hitlist-wrapper", "search-list-words", "search-list-word", "target-word", "rest-word"];
search_bar가 범용적으로 동작하려고 한다면, 
이런코드는 좀 아쉽죠. style 에 쓰이는 class이름이 하드코딩되어 있어서요.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +        if (this.isHitListOn() === false) {
명확한 false비교를 하고 싶으면 이럴 수 있지만 보통은 
if(this.isHitListOn()) 이라고 표현하긴 하죠.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +        if (target.classList.contains("search-list-words") || target.classList.contains("hitlist-wrapper")) {
조건문을, 배열의 indexOf 를 사용해서 수정해보세요.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.js
> +            if (target.innerHTML === "No Results Matched") {
이건 더 위로 올려서 빨리 체크해서 return 시키면 어때요?

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_bar.scss
> +            -webkit-appearance: none;
prefix 를 요즘은 도구가빌드할때 추가해주기도 해요.
하지만 이렇게 직접 추가해보는 것도 처음엔 좋죠.

2020-02-26 09:19 UTC, crongro commented on client/src/view/search_bar/search_list.js
> +        $('.hitlist-wrapper').style.display = "block";
이런 코드는 어떻게 만들까요? 
```
$('hit-wrapper').show().html('').setScrollTop(SCROLL_TOP_START);
```

2020-02-26 14:30 UTC, sangwon21 commented on client/src/view/search_bar/search_list.js
> +        $('.hitlist-wrapper').style.display = "block";
좋은 유틸 함수 거리를 제공해주셔서 감사합니다.

2020-02-26 14:32 UTC, sangwon21 commented on client/src/util/constants.js
> +    DEV: {
노드 환경에서는 process.env로 현재 개발하는 환경을 구별할 수 있을 것 같은데 브라우저에서는 그 환경을 어떻게 구별할 수 있을까요?

2020-02-26 14:35 UTC, sangwon21 commented on client/src/view/search_bar/search_bar.js
> +            if (target.innerHTML === "No Results Matched") {
빨리 return해도 괜찮을 것 같습니다.

2020-02-27 03:34 UTC, sangwon21 commented on client/src/view/search_bar/search_bar.js
> +        if (target.classList.contains("search-list-words") || target.classList.contains("hitlist-wrapper")) {
이 부분도 util 함수에 추가할 수 있을 것 같습니다.

2020-02-27 03:35 UTC, sangwon21 commented on client/src/view/search_bar/search_bar.js
> +        const inspectionClassList = ["hitlist-wrapper", "search-list-words", "search-list-word", "target-word", "rest-word"];
상수화 시키겠습니다...

2020-02-27 03:37 UTC, sangwon21 commented on client/src/view/search_bar/search_bar.js
> +        if (targetString === "") {
네 공백인 경우라면, 존재하는 setTimeout을 없애야 한다고 생각했습니다.

2020-02-27 03:38 UTC, sangwon21 commented on client/src/view/search_bar/search_bar.js
> +} from "../../util/constants.js";
네 하나의 객체로 만들어서 export, import해보겠습니다.

2020-02-27 08:03 UTC, sangwon21 commented
## 고치거나 바꾼 부분
- DOM 조작 중에 유틸 함수로 만들 수 있는 부분이 있어서 유틸 함수로 만들었습니다.
- destructuring 문법을 활용했습니다.
- 의미없는 스트링 상수들을 모아 enum화 시켰습니다.
- 서로 독립적으로 존재하던 상수들을 묶어 객체로 만들어서, 조금 더 명확한 의미를 찾을 수 있게 하였습니다. 

## 더 해볼 부분
- 로컬 서버를 이용해서 개발할 때, 고려하지 않았던 문제점, 응답 속도를 해결하는 방법을 찾아야 합니다.
- 특히, 데모 주소에 처음 들어갔을 때, 검색창이 보이지 않고 새로고침을 해야만 보이는 오류가 있는데 이를 해결해야 합니다.
- 동작 중에 사용자 예상과 다른 움직임들이 있어 보완해야 합니다.

2020-02-28 01:12 UTC, crongro approved these changes
좋아요~ 잘 수정해나가고 계심.

2020-02-28 01:12 UTC, crongro commented on client/src/util/constants.js
> +export const KEY_CODE = {
객체활용 좋네요.

2020-02-28 01:12 UTC, crongro commented on client/src/util/util.js
> +Element.prototype.show = function () {
Native 확장을 알아냈군요!
이렇게 사용하면 아주 개발할때 편리할 거 같네요.

그런데 단점이 한가지 있을꺼 같은데?  뭘까요?

2020-02-28 01:13 UTC, merged