[미션] Search_Amazon_검색자동완성
code-squad/javascript-amazon pull request #158
Opened 2020-02-26 09:42 UTC by Hu2y

### 미션 완료사항
- 필요한 데이터를 JSON형태로 만들기[검색단어는 영어단어 1000개]
- 로컬서버 환경을 구성(koa)
- 검색어 입력하게되면 해당 검색어가 자동완성 된 문자들을 화면에 나타나게 구현
- 입력창의 내용을 백스페이스로 삭제해도 일치하는 자동완성결과가 노출

### 추가로 할 사항
- 검색어와 일치하는 단어는 색깔이 하이라이트[span태그로 클래스를 줘서 적용]
- 자동완성 결과는 키보드 위/아래키로 이동[keyup, down 이벤트 등록으로 적용]
- 최근 검색결과 5개 보이도록 추가
- 데모페이지 올릴수 있게 호스팅 사이트 찾아보기
- webpack, babel 적용

해당 미션 완료한 후 이전 carousel 과제와 합치겠습니다.

> 구현 이미지
<img width="937" alt="스크린샷 2020-02-26 오후 6 07 29" src="https://user-images.githubusercontent.com/48382080/75331760-a13b2c00-58c6-11ea-8c8a-5fbba7cd3a6e.png">

2020-02-26 09:48 UTC, Hu2y commented
이전 프로젝트랑 분리해서 하고싶어서 폴더를 나눴는데.. 이전 커밋이 같이 날라갔습니다 

과제분리 커밋 부터 확인해주시면 감사하겠습니다!

2020-02-27 06:23 UTC, crongro commented
확인 가능한 데모 링크좀 추가해주세요 @Hu2y

2020-02-27 06:25 UTC, crongro commented
commit 단위도 좋고, 커밋로그도 좋네요.

2020-02-27 06:43 UTC, crongro requested changes
네 여기까지 좋네요.
controller를 만들어봤군요.
필수적인 건 아니지만, controller시도는 좋아요.
스스로 현재 controller의 역할에 대해서 잘 이야기할 수 있어야 합니다.

2020-02-27 06:43 UTC, crongro commented on carousel/view/carouselView.js
> +class Content {
Class를 작게 나눴기 때문에, 
하나의 파일에 관련된 클래스를 모아서 두는건 그래도 괜찮아보이네요.

2020-02-27 06:43 UTC, crongro commented on carousel/view/carouselView.js
> +    const buttons = this.items.reduce((render, button) =>
reduce를 친숙하게 사용하게 됐군요. 좋네요.

2020-02-27 06:43 UTC, crongro commented on search/client/src/controller/controller.js
> +  this.searchInput = $("#searchInput");
Controller 가 초기화될때 searchInput 와 autoList를 인자로 받아서 처리되도록 해도 될 듯.
searchModel객체도 주입받아서 동작해도 되고요.
그렇게 처리하면 의존성이 좀 줄겠죠

2020-02-27 06:43 UTC, crongro commented on search/client/src/controller/controller.js
> +Controller.prototype = {
Controller가 model, view의 연결고리 역할을 하는 건가요?
괜찮은 역할같아요. 잘했어요.

2020-02-27 06:43 UTC, crongro commented on search/client/src/controller/controller.js
> +    let message = e.target.value;
destructuring 문법을 활용해서 표현해보세요.

2020-02-27 06:43 UTC, crongro commented on search/client/src/controller/controller.js
> +    if (this.validateInput === true) {
if(searchInput) 라고 해도 뭐 큰문제는 없을 듯.

2020-02-27 06:43 UTC, crongro commented on search/client/src/controller/controller.js
> +      const connectModel = async () => {
connectModel함수를 내부함수로 만들지 않는게 더 좋을거 같긴해요.
중첩된 형태는 복잡해 보이기도 하고요.

2020-02-27 06:43 UTC, crongro commented on search/client/src/controller/controller.js
> +          await new autoCompleteView(this.searchModel.matchingItem, message);
await 다음에 객체를 초기화 하는데 autoCompleteView가 비동기 코드인가요?

2020-02-27 06:43 UTC, crongro commented on search/client/src/model/searchModel.js
> +  async fetchData(inputValue){
prototype객체를 오버라이딩 했으니 constructor 속성을 추가해야겠죠?

2020-02-27 06:43 UTC, crongro commented on search/client/src/model/searchModel.js
> +    const sleep = ms => new Promise(resolve  => setTimeout(resolve, ms));
유용한 sleep 함수는 유틸리티로 빼서 다른데서 재사용 할 수 있게 하는 것도 좋을 듯.

2020-02-27 06:43 UTC, crongro commented on search/client/src/model/searchModel.js
> +      if(matchingWord.indexOf(inputValue)=== 0) {
filter.forEach 순서로 써보는 것도 좋을 듯.

2020-02-27 06:43 UTC, crongro commented on search/client/src/model/searchModel.js
> +        this.matchingItem.push(matchingWord);
push하고 있군요. 그렇다면 filter.map 인듯

2020-02-27 08:55 UTC, Hu2y commented on search/client/src/controller/controller.js
> +      const connectModel = async () => {
넵!,  따로 함수로 분리 시켰습니다.
비동기 로직을 담은 함수는 IIFE를 적용 시켰습니다.

2020-02-27 08:56 UTC, Hu2y commented on search/client/src/controller/controller.js
> +          await new autoCompleteView(this.searchModel.matchingItem, message);
랜더해주는 부분이라 비동기 코드가 아니여서 awiat 부분 지워주도록 하겠습니다!

2020-02-28 01:18 UTC, crongro approved these changes
금새 수정하셨네요.
수고하셨네요.
여기까지 승인/머지합니다~!

2020-02-28 01:18 UTC, crongro commented on search/client/src/controller/controller.js
> +        new autoCompleteView(this.searchModel.matchingItem, message);
그런데 약간 어색해보이는 것이 있어요.
비동기로 데이터를 받아왔으면 그 결과를 autoCompleteView에 넣어줘야 할 거 같은데,? 그게 숨겨서 처리되는 거 같네요.

이런식으로 보여지면 좋겠는데요. 어떻게 데이터가 전달되는지 보여지도록요.

const result = await fetch();
new autoComplteView(result)

2020-02-28 01:18 UTC, crongro commented on search/client/src/controller/controller.js
> +    } else if (this.autoListIndex > 0 && this.autoListIndex < this.searchList.childElementCount) {
이 조건문은 조금 긴편입니다.

2020-02-28 01:18 UTC, crongro commented on search/client/src/controller/controller.js
> +    if(method === 'add') {
때로는 switch 문이 어울리는 경우가 있죠.
지금경우 case가 add, remove 등으로 정해져 있어서 그런지 switch 가 좀더 생각나네요.

2020-02-28 01:18 UTC, crongro commented on search/client/utlis.js
> +Array.prototype.selectClassList = function ({targetClass, method, addClassName, index}) {
네이티브 확장은 편리한데,  단점이 하나 있어요. 
안티패턴으로 알려져 있지 않은지 한번 검색해보세요~ 왜 그런지도 알아보고요.

2020-02-28 01:18 UTC, merged