Search 미션 제출
code-squad/javascript-amazon pull request #159
Opened 2020-02-26 14:37 UTC by seungdeng17

데모 : https://seungdeng17.github.io/amazon-DEMO/

- **수정** - fetch 미션에서 피드백 받은 내용을 수정했습니다.
destructuring 활용 -> Slide 옵션값을 변수화
옵션값 대문자 -> 소문자
if문 긴 조건식 함수로 분리
NavCard 이벤트 등록 event delegation 방식으로 변경

- **search 미션 구현**
영단어 1000개에 대한 자동완성결과 노출 (최대 10개까지 응답)
300ms 지연 후 화면에 추가
입력과 일치하는 단어 하이라이트

- **추가 할 것**
방향키 위/아래 입력 시 이동, 엔터키 입력 시 input창에 추가
최근 검색 결과 노출

혼자 하니 외롭고 맞게 가고 있는지 의구심이 들어 중간 PR을 보냅니다!
리뷰 감사합니다!!

2020-02-27 07:18 UTC, crongro requested changes
전체 왁꾸(?)는 좋습니다.

리뷰 남긴건 참고해서 수정하고, 기능을 추가해서 다시 push!

2020-02-27 07:18 UTC, crongro commented on index.html
> +    <link rel="stylesheet" type="text/css" href="./src/css/searchStyle.css">
실제 배포에서는 css를 http request를 줄이는 차원에서 합쳐서 배포합니다.
merge한다고 하죠.

2020-02-27 07:18 UTC, crongro commented on server/app.js
> +app.use(bodyParser.raw());
시간되면 app.js내의 서버설정들이, 
각각 의미하는 것들이 어떤것인지 훑어보고 넘어가면 좋겠네요.

2020-02-27 07:18 UTC, crongro commented on server/public/json/localData.json
> +                "1988. 5. 12, Brazil",
오 영어버전~

2020-02-27 07:18 UTC, crongro commented on server/routes/wordSearch.js
> +    console.log(input);
PR 보낼때 console 지우기!
디버깅은  breakpoint 활용!

2020-02-27 07:18 UTC, crongro commented on server/routes/wordSearch.js
> +    const result = [];
result보다는 좀더 구체적인 이름으로~

2020-02-27 07:18 UTC, crongro commented on server/routes/wordSearch.js
> +    for (let i = 0; i < wordData.words.length; i++) {
for문을 없애고 map을 한번 써볼래요?

2020-02-27 07:18 UTC, crongro commented on src/js/lib/util.js
> +export function taek$(target) {
util 좋아요. 자꾸 늘려보세요.

2020-02-27 07:18 UTC, crongro commented on src/js/main.js
> +main();
main은 즉시실행함수로 표현해도 될 듯.

2020-02-27 07:18 UTC, crongro commented on src/js/main.js
> +        fetch("http://localhost:8080/json/localData.json")
URL을 적어도 함수의 인자로 받는 게 어떨까요? 이런게 하드코딩되어 있는건 안좋습니다.
url은 변경될 수 있거든요. 개발단계의 URL과 실제 배포시의 URL이 다르기도 하고요.

2020-02-27 07:18 UTC, crongro commented on src/js/search/searchBar.js
> +    constructor: SearchBar,
👍

2020-02-27 07:18 UTC, crongro commented on src/js/search/searchBar.js
> +            .then(json => {
여기 then함수 인자로 들어가는 함수를 분리해보세요.

2020-02-27 07:18 UTC, crongro commented on src/js/search/searchBar.js
> +            this.timer = setTimeout(this.wordDataRequest.bind(this), 300, input);
오 setTimeout 세번째인자!!
브라우저 호환성도 한번 확인해보세요.

2020-02-27 07:18 UTC, crongro commented on src/js/search/searchBar.js
> +            body: input
데이터가 잘 전송되는지 개발자도구의 네트워크 탭을 확인해보시죠!

2020-02-27 07:18 UTC, crongro commented on src/js/search/searchList.js
> +        data.forEach(word => {
reduce로 고쳐봅시다. 
좀더 간결하게요.

2020-02-27 13:51 UTC, seungdeng17 commented on src/js/search/searchList.js
> +        data.forEach(word => {
reduce를 쓰면 지역변수를 쓰지 않아도 될 것 같아요 감사합니다!

2020-02-27 14:02 UTC, seungdeng17 commented on src/js/main.js
> +main();
오늘 강의를 통해 즉시실행함수를 알게되었습니다. 다음 리팩토링에 적용해보도록 하겠습니다!

2020-02-27 14:05 UTC, seungdeng17 commented on server/routes/wordSearch.js
> +    for (let i = 0; i < wordData.words.length; i++) {
서버의 부하를 줄이기 위해 클라이언트로 보낼 데이터의 양이 maximum이 됐을 때 반복문이 break 되는 것을 구현하고 싶었습니다.
사용해 본 방식은 reduce, some이 있었지만 원하는 대로 되지 않았어요..ㅜ 다음엔 추천해주신 map을 적용해보도록 하겠습니다.

2020-02-28 08:24 UTC, seungdeng17 commented on index.html
> +    <link rel="stylesheet" type="text/css" href="./src/css/searchStyle.css">
방학기간을 이용해서 webpack을 공부하도록 하겠습니다!

2020-03-04 02:41 UTC, crongro approved these changes
수고하셨네요. 
리뷰 남기고 머지승인합니다~

2020-03-04 02:41 UTC, crongro commented on server/app.js
> +var slideDataRouter = require('./routes/slideData');
node코드도 es6문법을 사용하는게 좋겠네요.

2020-03-04 02:41 UTC, crongro commented on server/routes/wordSearch.js
> +        if (acc.length >= maximum || !word.startsWith(input)) return acc;
maximum 보다는 maxCount라던가 뭔이 이름을 제대로~

2020-03-04 02:41 UTC, crongro commented on src/js/common/url.js
> +    PROD: {
좋네요.
보통 production 을 잘 줄이지는 않아요.

2020-03-04 02:41 UTC, crongro commented on src/js/search/options.js
> +const options = {
options내용은 분리하는 것보다 searchBar에 두고 의도를 드러내는게 좀더 좋다고 생각되네요.

2020-03-04 02:41 UTC, crongro commented on src/js/search/searchList.js
> +                if (this.curList !== null) {
이만큼정도도 함수로 분리할 수도 있긴하죠.
```javascript
if (this.curList !== null) {
  evt.preventDefault();
  classRemove(taek$(".search-blind"), "on");
  this.searchListOff();
  this.listInit();
  this.searchInput.value = this.curList.innerText;
```

2020-03-04 02:41 UTC, crongro commented on src/js/search/searchList.js
> +    curListStateCheck(isKeyDown) {
checkCurrentListState 라고 하는게 명확할 듯.

2020-03-04 02:41 UTC, crongro commented on src/js/search/searchList.js
> +        if (this.curList === null) return true
로직이 맞다고 하더라도, 
null인데 true를 반환하는 것이 어색해보이네요. 음

2020-03-04 02:41 UTC, crongro commented on src/js/slide/dataRender.js
> +            return new Promise(resolve => {
promise를 반환시켰군요. 
나중에 async함수를 사용하면 promise객체로 자동반환 되긴합니다.

2020-03-04 02:41 UTC, merged