[Vahn - Step4] Add rotating mini carousel
code-squad/javascript-amazon pull request #16
Opened 2018-12-21 14:11 UTC by Vanary

미니 캐로셀을 추가했습니다.

- 궁금한 점: 모듈로 구현할 때 궁금한 점이 두 가지 있습니다.
  - 모듈이 여러 공용 모듈을 import할 때, 어떻게 하면 간결한 코드로 모듈들을 불러다 쓸 수 있을까요?
  - 클래스를 extend해서 메서드를 가져다 쓰는 패턴을 시험해봤습니다. => 부모 클래스의 메서드가 맥락없이 코드에 튀어나오니, 협업할 때 코드 가독성이 걱정됩니다. 해당 문제를 해결하는 패턴이 있을까요? (빌려온 메서드에는 super 키워드를 붙여서 표시한다던지..)

- 기타: stickyNav에 치명적인 버그가 있었습니다. 호호.. 해당 내용이 수정되었습니다.

- 데모 페이지 <https://vanary.com/javascript-amazon/>

2018-12-21 14:15 UTC, Vanary commented on scripts/miniCarousel/MiniCarousel.js
> +      setTimeout(() => {
GitHub 이미지 호스팅이 느려서 그런지,  
DOM 노드는 추가되었는데 이미지 다운이 느려지면서 UI가 깨지는 경우가 있었습니다.

해당 문제를 해결하려고 이미지 다운로드를 잠시 기다려보도록 코드를 추가했습니다.  
현장에서 해결책으로 쓰는 fallback 전략이 궁금합니다 ^^~

2018-12-23 23:31 UTC, nigayo commented
> * 모듈이 여러 공용 모듈을 import할 때, 어떻게 하면 간결한 코드로 모듈들을 불러다 쓸 수 있을까요?

구현한 코드중에 여러모듈을 불러오는 예제는 안보이는데요. 더 많아져도 지금 처럼해야하죠
저도 import한 모듈을 함수단위로 다 노출해서 직접 접근하는 식으로 많이 짜요.

(지저분하쥬 ㅋ)

```
import { getPRDataPromise, getRepoPromise, getStudentPromise, getPRInfoList} from "./dataProcessor/prInfoMaker.js"
import { setColumnLabel } from "./tableView/renderColumnLabel.js"
import { renderInitialData, appendTableNode} from "./tableView/renderTable.js"
import { updateLoadingProgress } from "./loadingView/loadingView.js"
import { $ } from "./lib/_.js"
```

as 를 사용해서 별명을 지정해서 하는 것도 해보세요.
import * as name....

2018-12-23 23:45 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +      this.animFrame.funcOnDebounce = this.debounce(this.startAutoRotate, 5000).bind(this);
super로 자식의 동일메서드와 구별할 수도 있죠.
super를 더 사용하는 것이 좋은 방법입니다. 

그리고 그전에 상속이 복잡한 관계이면, 이것이 누구의 메서드인지? 가독성은 떨어질 수밖에 없어요.
상속의 단점이죠.

2018-12-23 23:45 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +      setTimeout(() => {
어떻게 깨졌는지 모르겠지만 로딩이후에 처리되도록 하는게 안전하겠죠.

많이 느린것이면, image onload 이벤트를 써보면 어때요? 
그 이후에 처리되도록 해야할 듯.

2018-12-23 23:58 UTC, crongro requested changes
잘 구현했어요.
css속성을 잘 사용했고, classname을 바꿔주는 전략도 좋습니다.

옵션을 좀더 강화해서 3~5개에서도 동작하는 더 범용적인 컴포넌트로 동작되도록 해볼래요?

2018-12-23 23:58 UTC, nigayo commented on css/miniCarousel.css
> +  width: 34rem;
rem 잘 사용했어요.

2018-12-23 23:58 UTC, nigayo commented on css/miniCarousel.css
> +  transform: translate(-50%, -50%);
gpu가속이 지원되는 속성들은 메인쓰레드를 방해하지 않아서 좋다고 하죠.
그런 css속성을 모두 찾아서 무엇인이 알아보세요~ 
opacity등~

2018-12-23 23:58 UTC, nigayo commented on css/miniCarousel.css
> +  transition: all 0.1s;
지금은 거의 필요없는 시대긴한데요. 
vendor prefix라는 것이 있었어요. 최신css스펙이 표준으로 정착하기 전에 브라우저벤더들이 저마다 prefix를 만들어서 사용하곤했죠.
사용예를 살펴보세요.

2018-12-23 23:58 UTC, nigayo commented on res/primeOriginal.json
> +[
잘 했음~

좀더 복잡한 데이터를 만지작거려야 한다면(수정/추가등까지 해야하면)
나중에 데이터정규화에 대해서도 공부하면 더 좋음.

2018-12-23 23:58 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +    xhr.addEventListener('load', this.setCarouselInnerHTML.bind(this));
이벤트핸들러를 잘 분리했어요.

2018-12-23 23:58 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +  setListenerToController() {
이벤트 등록 코드들을 모아두는 건 좋은방법이에요.

2018-12-23 23:58 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +    [...cards].forEach(card => this.updateCardClass(card, updator));
nodeList에는 forEach메서드가 native로 있어요~

2018-12-23 23:58 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +      return num === 1 ? '4' : `${num - 1}`;
클래스 순서를 바꾸는 작업으로 구현해서 좋아요~

panel이 4개가 아니고 3개, 5개라도 코드 수정을 최소한으로 해서 동작되게 한번 수정해보세요!

2018-12-23 23:58 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +      this.animFrame.funcOnDebounce = this.debounce(this.startAutoRotate, 5000).bind(this);
5000 이런 매직넘버를 클래스생성시 옵션으로 받는게 더 좋을 거 같아요.

2018-12-23 23:58 UTC, nigayo commented on scripts/main.js
> +  htmlElSelector: '.horizontalBanners__prime-music',
옵션으로 이런값을 주는 것은 좋고요. 객체형태도 잘 활용했어요.

엘리먼트 말고 다른 option value더 추가할 수 있겠죠.
필요하면 함수도 옵션으로 넣어줄 수 있고요.

2018-12-23 23:58 UTC, nigayo commented on scripts/miniCarousel/MiniCarousel.js
> +  createLiHTMLWithJSON({ id, src, alt }) {
지금처럼 template 를 별도 함수로 분리해두는 게 좋아요.

2018-12-24 07:19 UTC, Vanary commented on css/miniCarousel.css
> +  transform: translate(-50%, -50%);
paint없이 GPU를 통해 composition만 발생시키는 CSS 속성들을 알아봤습니다. (예: opacity, transform, perspective)  
그 과정에서, 해당 값들을 바꿀 예정이라면 미리 layer를 만들어 (예: translateZ(0)) 두라는 조언도 얻었습니다.

2018-12-24 07:19 UTC, Vanary commented on css/miniCarousel.css
> +  transition: all 0.1s;
CSS 속성들 브라우저 호환성볼 때 종종 보이더군요!  
Autoprefixer와 CSS 표준 확대에 기대를 걸어보면서 계속 공부하겠습니다.

2018-12-24 07:26 UTC, Vanary commented
아래와 같이 개선했습니다

- 캐로셀 갯수 제약 확대: 9개 카드까지 유연하게 처리
- magic number 삭제: 캐로셀 회전 타이밍 관련 수치를 객체 생성시에 인자로 받음
- image 다운로드 지연 처리 개선: setTimeout을 삭제하고, HTMLImageElement.complete 속성을 이용

2018-12-26 03:45 UTC, crongro approved these changes
잘 수정했어요~

정리하시고 다음단계로!

2018-12-26 03:45 UTC, nigayo commented on css/miniCarousel.css
> +  height: calc(var(--horizontal-banner-height) * 0.7);
IE지원때문에 css function을 쉽게 못쓰는 상황이긴해요.,
sass 와 같은 것을 나중에 사용하시고, transpiling함으로써 브라우저 호환성 문제 없이 사용할 수 있어요.

2018-12-26 03:45 UTC, nigayo commented on scripts/main.js
> +  timer: miniCarouselTiming,
옵션값들을 객체로  전달해주는 건 좋아요.

이런 재사용 컴포넌트의 다양한 예제코드를 한번 살펴보세요.
https://naver.github.io/billboard.js/demo/

2018-12-26 03:46 UTC, merged