[미션] 검색자동완성
code-squad/javascript-amazon pull request #160
Opened 2020-02-26 14:59 UTC by dev-angelo

Demo page: https://dev-angelo.github.io/amazon-clone/

**완료 사항 >**

* 검색어를 입력하면 자동완성결과가 노출된다. 
* 자동완성결과는 바로 추가되지 않고, 300ms지연 후에 화면에 추가된다. 
* 입력창의 내용을 백스페이스로 삭제해도 일치하는 자동완성결과가 노출된다. 
* 자동완성 결과는 키보드 위/아래키로 이동할수 있다.
* 자동완성 결과를 키보드 방향키로 이동시에 선택부분의 배경색은 변경된다. 선택된 상태에서 엔터키를 입력하면 해당검색어가 위쪽 검색input창에 추가된다.  동시에 검색결과창은 사라진다.
* 검색버튼을 눌러도 검색이 이뤄지진 않으며, 자동완성 결과 창은 닫힌다. 

**미완료 사항 >**
* 노출된 데이터 중 검색어와 일치하는 단어는 색깔이 하이라이트 되여 보여진다.
* (선택기능) 검색창에 포커스가 가면, 최근 검색한 결과가 최대 5개까지 노출된다. (시간 역순으로 최근 검색한 내용이 위에 나옴)

**힘들었던 부분 >**
* MVC 패턴 을 이 익숙하지 않아서 (기존의 지식은 특정 프레임워크에 특화된 
  MVC 패턴? 이었습니다.) 구조가 헷갈려 코딩을 하면서도 의문이 들었습니다.

**아쉬웠던 부분 >**
* Browser 에서는 EventEmitter 를 사용 할 수 없어서 많은 부분을 callback 으로 처리.

**To do >**
 **요구사항 관련:**
 * 노출된 데이터 중 검색어와 일치하는 단어는 색깔이 하이라이트 되여 보여진다.
 * (선택기능) 검색창에 포커스가 가면, 최근 검색한 결과가 최대 5개까지 노출된다. 
   (시간 역순으로 최근 검색한 내용이 위에 나옴)

**기타:**
  * MVC 패턴을 더 공부하여 구조 변경 필요시 구조 변경.
  * 기 구현되어 있던 Slide 를 MVC 패턴으로 마이그레이션.

**그 외 >**
* Demo 를 위한 Github Pages 는 http 프로토콜을 허용하지 않아서 의도하지는 않았지만
  Apache Server, DDNS, SSL, SSL 인증키 발급 방법, SSL 인증키를 express 서버에 적용 등을
  알게 되었습니다. 

**질문사항 >**
* View 는 사용자에게 보여지는 내용들을 위한 계층인데, 
  render 함수 외에도 사용자에게 화면이 변경되는 내용들을 설정하는 DOM 조작 
  (controller 에서 suggestion list 가 변경되었다는 것을 view 에서 전달 받아
   appendChild 등의 함수를 통해 사용자에게 보여질 자동완성 리스트 구성 등)
  도 View 에서의 역할이라고 생각 할 수 있을까요?

2020-02-27 07:30 UTC, crongro commented
> View 는 사용자에게 보여지는 내용들을 위한 계층인데,
> render 함수 외에도 사용자에게 화면이 변경되는 내용들을 설정하는 DOM 조작
> 
> 1. controller 가 서버로부터 받은 response 로 model 을 설정 하고,
> 2. controller 는 model 로부터에서 suggestion list 가 변경되었다는 것을 전달 받아
> 3. 그 내용을 view 로 전달하여
> 4. view 에서는 appendChild 등의 함수를 통해 사용자에게 보여질 자동완성 리스트 구성 등
> 
> 도 View 에서의 역할이라고 생각 할 수 있을까요?

view가 데이터 조작과 변경을 할 수도 있긴하지만
이미 설명하신대로
controller  같은 중간 단계가 view에서 보여줄 데이터를 가공하는 것도 좋죠.
개인적으로는 view가 순수해지면 view를 재사용할 수 있어서 좀더 좋은거 같아요.

2020-02-27 07:53 UTC, crongro requested changes
컨트롤러 역할을 둔 게 인상적이네요.
좋은 시도고, 역할도 괜찮아보여요. 특히 view와 모델의 의존성을 줄인점이 잘한거죠. 
🥇 

기능이 많아지면,  컨트롤러가 매우 커질 수도 있다는 점을 염두해야겠고요, 
view에서 일어나는 event 등록을 파악하기 어렵다는 점도 단점일 수 있죠.

어떤 패턴이던 장단점이 있는데, 스스로 이부분을 판단해보는 연습이 필요합니다. 

시간되면, 
- debounce 기능을 도전해보세요 (타이핑시간 간격이 일정시간 멈추어 있으면 서버로 전송하도록)
- 캐시해서 서버로 안가도록 해보세요.(메모리에 캐시)

일단 request changes 상태로 둡니다. push하세요!

2020-02-27 07:53 UTC, crongro commented on Search/SearchAutoCompletionView.js
> +    render() {
render 라는 이름 좋아요.

2020-02-27 07:53 UTC, crongro commented on Search/SearchAutoCompletionView.js
> +    onNotifySuggestionChanged(suggestion) {
controller에서 접근하는 경우 on으로 구별지어서 이름지으신 거 괜찮네요.

2020-02-27 07:53 UTC, crongro commented on Search/SearchAutoCompletionView.js
> +            this._changeHeight(this.searchSuggestion.childElementCount * parseInt(getComputedStyle(this.searchSuggestion.firstElementChild, null).getPropertyValue("height")));
이 가로로 뻗어 있는 코드를 빨리 ...해결해주세요 ㅎ

2020-02-27 07:53 UTC, crongro commented on Search/SearchAutoCompletionView.js
> +        while(this.searchSuggestion.hasChildNodes()) {
반복문 잘 썼음!

2020-02-27 07:53 UTC, crongro commented on Search/SearchBackgroundView.js
> +class SearchBackgroundView {
backgroundview 라는 이름이 구조를 의미하니까, 맥락을 파악하기 어렵네요.

2020-02-27 07:53 UTC, crongro commented on Search/SearchController.js
> +        const search = document.querySelector('.search');
searchNode라고만 해도 좀더 나을 듯.

2020-02-27 07:53 UTC, crongro commented on Search/SearchController.js
> +        search.addEventListener('click', event => this._handleClickEvent(event));
이벤트 등록 3개를 세줄로 표현한게 간결하고 맥락파악도 잘 되고 좋네요.

2020-02-27 07:53 UTC, crongro commented on Search/SearchController.js
> +    _appendBind() {
private 를 _ 붙여서 표현한거 좋긴해요. 자주 사용하기도 하고요.
앞으로는 이런속성이 추가된다고 하니, 살펴보세요.
https://github.com/tc39/proposal-private-methods

2020-02-27 07:53 UTC, crongro commented on Search/SearchController.js
> +            const focusedElement = (document.querySelector(".searchSuggestion").querySelectorAll("li"))[this._model.getCurrentIndex()];
여기도 가로가 너무 긴 코드..좀 줄이면 좋겠습니다. 
변수를 활용해보세요.

2020-02-27 07:53 UTC, crongro commented on Search/SearchController.js
> +            }, 300);
300 하드코딩 보다는 미리 이름을 지어주고 사용하는 것이 좋을 듯.

2020-02-27 07:53 UTC, crongro commented on Search/SearchController.js
> +                'Content-Type': 'application/json',
json형태로 보내는거군요. 좋아요.

2020-02-27 07:53 UTC, crongro commented on main.js
> +    const searchController = new SearchController(new SearchModel(), new SearchView());
객체를 생성해서 이렇게 주입시켜주는 거 좋네요.

2020-02-27 17:11 UTC, dev-angelo commented
> 컨트롤러 역할을 둔 게 인상적이네요.
> 좋은 시도고, 역할도 괜찮아보여요. 특히 view와 모델의 의존성을 줄인점이 잘한거죠.
> 🥇
> 
> 기능이 많아지면, 컨트롤러가 매우 커질 수도 있다는 점을 염두해야겠고요,
> view에서 일어나는 event 등록을 파악하기 어렵다는 점도 단점일 수 있죠.
> 
> 어떤 패턴이던 장단점이 있는데, 스스로 이부분을 판단해보는 연습이 필요합니다.
> 
> 시간되면,
> 
> * debounce 기능을 도전해보세요 (타이핑시간 간격이 일정시간 멈추어 있으면 서버로 전송하도록)
> * 캐시해서 서버로 안가도록 해보세요.(메모리에 캐시)
> 
> 일단 request changes 상태로 둡니다. push하세요!

질문이 있습니다~

* debounce 관련
debounce 관련 요구사항을 말씀 해 주셨는데, 사용자 입력중 dim 처리 된 영역 클릭 등으로 인하여 dim background & 추천단어 가 사라지고 input field 가 focus 를 잃어버린 후에 사용자가 다시 input field 를 클릭 하여 focus 상태가 됐을때를 의미하는 것인가요?

* 캐싱 관련
미션과는 관련이 없지만, 실제 서비스에서는 서버의 특정 알고리즘에 따라서 같은 단어를 
입력하더라고 한달전의 추천어와 오늘의 추천어가 다를 수 있는데 
-------------------------------------------------------------------------
실제 서비스에서는 캐싱유무와 별개로 사용자 입력이 발생하면 
1. Client 는 서버에 사용자 입력에 대한 추천단어 전달.
2. 서버는 사용자 입력에 대한 메타데이터? 를 Client 에게 전달
3. Client 는 메타데이터를 키값으로 하는 데이터가 캐싱 되어 있는지 확인.
3-1. 캐싱 되어 있다면 suggestion 은 요청하지 않음
3-2. 캐싱이 되어 있지 않다면 suggestion 요청
4. 3-2 의 경우 서버는 suggestion 전달

와 비슷한 과정을 거치는것이 맞는것인지 궁금합니다.
---------------------------------------------------------------------------
이때의 캐싱은 이번 미션과의 캐싱과는 다르다고 봐도 괜찮을까요?
(이번 미션에서는 Server 에서의 추천 단어가 바뀌지 않는다는것을 가정하기 때문.)

2020-02-28 01:35 UTC, crongro approved these changes
수정을 잘하고 계시네요.
(_)를 변수에 붙이는 건 필수는 아닌 거 같아요. ㄱ ㅐ발자마다 의견이 다른부분이고요.

2020-02-28 01:35 UTC, crongro commented on Search/SearchAutoCompletionView.js
> +        this._searchSuggestion.addEventListener('click', event => this._onSuggestionClicked(event));
this때문에 화살표 함수로 감싼거죠? 그렇다면 괜찮네요! bind를 사용한 해법도 알아두시고요.

2020-02-28 01:35 UTC, crongro commented on Search/SearchController.js
> +            arrowDownPressHandler: this._handleArrowDownPress.bind(this),
bind를 다 해주었는데, 정말 다 필요한 것인지는 한번 확인하시고 사용하시고요.

2020-02-28 01:35 UTC, crongro commented on Search/SearchController.js
> +        if (cachedData) {
else문 없애기.

```
if(cachedData) { 
  setTimeout();
  return
}

fetch().then().then();
```

2020-02-28 01:35 UTC, crongro commented on Search/SearchController.js
> +        const focusedElement = (document.querySelector(".searchSuggestion").querySelectorAll("li"))[this._model.getCurrentIndex()];
너무 긴 표현이에요. 중간 값을 변수로 저장해주세요~

2020-02-28 01:36 UTC, crongro commented
> * debounce 관련 요구사항을 말씀 해 주셨는데, 사용자 입력중 dim 처리 된 영역 클릭 등으로 인하여 dim background & 추천단어 가 사라지고 input field 가 focus 를 잃어버린 후에 사용자가 다시 input field 를 클릭 하여 focus 상태가 됐을때를 의미하는 것인가요?

아니요. 
예를들어 입력중에는 서버로 요청이 안가는 것이고요.  예를들어서 500ms동안 입력이 없다고 판단되면 서버로 요청을 보내는거죠.

2020-02-28 01:37 UTC, crongro commented
> * 미션과는 관련이 없지만, 실제 서비스에서는 서버의 특정 알고리즘에 따라서 같은 단어를
>   입력하더라고 한달전의 추천어와 오늘의 추천어가 다를 수 있는데
>   이때의 캐싱은 이번 미션과의 캐싱과는 다르다고 봐도 괜찮을까요?
>   (이번 미션에서는 Server 에서의 추천 단어가 바뀌지 않는다는것을 가정하기 때문.)

네 맞아요. 원래는 실시간 변경이 될 수 있는건 캐시하면 안되겠죠 ^^

2020-02-28 01:37 UTC, merged

2020-02-28 01:41 UTC, dev-angelo commented on Search/SearchController.js
> +        const focusedElement = (document.querySelector(".searchSuggestion").querySelectorAll("li"))[this._model.getCurrentIndex()];
리팩토링을 진행을 먼저 해서 리뷰 받은 부분에 대해서 다시 pr 하도록 하겠습니다~!

2020-02-28 01:42 UTC, dev-angelo commented on Search/SearchController.js
> +            arrowDownPressHandler: this._handleArrowDownPress.bind(this),
넵! 이 부분 확인 해 보도록 하겠습니다