[리오] Amazon 2 : Carousel - STEP 4
code-squad/javascript-amazon pull request #20
Opened 2019-01-09 05:16 UTC by feanar729

오랜만에 PR이군요.
리뷰 부탁드립니다.

2019-01-11 05:42 UTC, crongro requested changes
기능을 보완하고 다시 PR!
코드의 틀은 괜찮아보여요

2019-01-16 07:58 UTC, feanar729 commented
refactoring 진행 완료 되었습니다 
아래는 데모페이지 입니다 리뷰 부탁드립니다.
https://feanar729.github.io/javascript-amazon/

2019-01-16 08:09 UTC, crongro requested changes
잘 동작합니다 👍 
이벤트 등록 과 함수 나눈 것등 코드의 품질도 좋아요.

리오를 사랑하는 마음에, 두 가지만 더 부탁할게요.

- panel의 갯수가 4개가 아닌 n개 일때도 Carousel 클래스의 큰 수정없이 동작하도록 구현해보세요. 
- debounce 를 적용했으니, 동작원리에 대해서 짧은 블로그 수준으로 내용을 정리해서 markdown등의 형식으로 작성해주세요.

수정 그리고 문서작성 후에 다시 PR부탁드려요!

2019-01-16 08:09 UTC, nigayo commented on js/carousel.js
> +    this.carousel.ulLayer.removeEventListener("transitionend", this.setRightSlide);
transitionend 를 잘 기억해서 활용하도록 하세요.
애니메이션간의  종료타이밍을 정확히 알 수 있어서 유용해요.

2019-01-18 04:50 UTC, feanar729 commented
요구하신 조건 2가지 
- Panel n개일 때 Carousel 동작
- Debounce 블로그 작성 
> 링크: https://medium.com/@feanar729/debounce%EB%9E%80-%EB%AD%98%EA%B9%8C%EC%9A%94-82204c8b953f

2019-01-18 09:03 UTC, crongro approved these changes
좋아요. 추가요구사항 하느라 수고했어요~

이제 다음 step고고!

2019-01-18 09:03 UTC, nigayo commented on js/carousel.js
> +    this.setAutoActTimer = 3000;
new Carousel({autoactimer : 2000}) 
이런식으로 옵션으로 받으면 이렇게 하드코딩하지 않게 되겠죠?

2019-01-18 09:03 UTC, nigayo commented on js/carousel.js
> +    this.setAutoActTimer = 3000;
default parameter를 잘 활용해도 좋고요.

2019-01-18 09:04 UTC, merged