[Torco]Step4 - Carousel
code-squad/javascript-amazon pull request #21
Opened 2019-01-09 11:38 UTC by cohily12

- 크롱이 말씀하신 transitionend event를 적용해보았습니다.
- 최대한 모듈로 나누어 구현하려고 노력하였습니다.
- ajax를 통해 carousel에 필요한 이미지 json파일을 불러와 기능구현하였습니다.

* setTimeout 혹은 setInterval을 사용한 부분에서 사용해도 되는지? 아니면 말씀하신대로 비동기제어를 위해 이런 방식으로 사용하면 안되는 지 궁금합니다.

* ajax, carousel, htmltemplate 등 모듈로 나누어 작업하다보니 변경점에 대해 코드 수정을 쉽게 할 수 있었습니다.

피드백 주시면 감사하겠습니다.

2019-01-09 11:39 UTC, cohily12 commented
p.s 아 그리고 domcontentloaded 이벤트에 적용한 코드가 적절한 지 궁금합니다. 아직 domcontentloaded가 어떻게 적절히 사용되야하는지 의문입니다..ㅎ

2019-01-11 05:24 UTC, crongro requested changes
수고하셨어요~
잘 구현했고요.

리뷰참고해서 조금 수정해보세요.

그리고 git-page에 데모를 볼 수 있게, 코드를 올리면 좋겠습니다.
어렵지 않으니 한번 배워서 해보세요.

2019-01-11 05:24 UTC, crongro commented on css/prime_carousel.css
> +    display: flex;
flex를 몇군데 쓴거같네요. 
layout잡을때 요즘은 많이 쓰고 있으니 잘 기억해서 사용하세요~

2019-01-11 05:24 UTC, crongro commented on js/app.js
> +document.addEventListener("DOMContentLoaded", () => {
이부분을 각각의 View기준의 파일들로 옮기는 게 좋겠어요.
app.js에서는, 많은 파일들의 초기화정도만 하는게 좋아요. 
그래야 이 페이지에서 어떤일들이 일어나는지  그리고, 모듈간에 어떤관계가 있는지, 빠르게 알 수 있어요.

2019-01-11 05:24 UTC, crongro commented on js/module/Ajax.js
> +class Ajax {
어제말한 것처럼 객체리터럴로 유틸리티 묶음으로 관리하면 더 좋을 듯.

2019-01-11 05:24 UTC, crongro commented on js/module/Carousel.js
> +        }, 3000);
3000, 5000 이런값은 변경될 수 있음으로, 
 Carousel컴포넌트의 생성자의 인자로 받는 게 어떨까 싶네요.

2019-01-11 05:24 UTC, crongro commented on js/module/HTMLTemplate.js
> +            const resultHTML = jsonData.reduce((HTML, img) => {
reduce잘 썼음니다.

2019-01-11 05:24 UTC, crongro commented on js/module/Scroll.js
> +class Scroll{
scroll.js는 사실 뭐를 하는 것인지 모르겠어요.
scroll을 처리하는 맥락이 안보입니다.

2019-01-11 05:24 UTC, crongro commented on js/module/StickyLayer.js
> +                hiddenBar.classList.add("visible");
classList의 toggle 도 있으니 참고하세요.

2019-01-11 05:24 UTC, crongro commented on js/module/Carousel.js
> +        this.prevBtn.addEventListener("click", () => {
this.prevBtn 속성은 run함수에서만 사용하면, 클래스 속성으로 정의하지말고 
함수의 지역변수로 지정하면 될 듯.
유효범위를 작게하는게 늘 좋죠. 다른 함수로 인한 변경확률도 적고요.

2019-01-11 05:24 UTC, crongro commented on js/module/HTMLTemplate.js
> +class HTMLTemplate {
이것도 클래스일 필요가 없어보이는데요.
객체로 묶어두기만하고, 이를 export하면 될 듯.
또는 함수로만 정의하고 export하기.

2019-01-13 16:03 UTC, cohily12 commented
리뷰 주신 사항 수정해보았습니다.

피드백 주시면 감사하겠습니다.

2019-01-13 16:53 UTC, cohily12 commented
아 데모 페이지 링크를 빼먹었네요
demo: https://cohily12.github.io/javascript-amazon

2019-01-14 11:03 UTC, nigayo commented
동작이 일단 매끄럽네요. 무척이나~
💯

2019-01-14 11:07 UTC, crongro approved these changes
👍 잘했소.

2019-01-14 11:07 UTC, nigayo commented on js/app.js
> +window.addEventListener("load", () => {
잘 했어요~ 
특별한 경우가 아니면, DOMContentLoaded 를 쓰는 게 좋긴합니다.

2019-01-14 11:07 UTC, nigayo commented on js/init.js
> +ajax.getReq("https://cohily12.github.io/javascript-amazon/json/options.json")
실제 서비스에서는 이렇게 URL문자열을 소스코드(로직이 있는)에 하드코딩하면 안되겠죠. URL은 변경될 수 있기때문이죠.
별도 config.js와 같은데 모아서 관리하는 것도 좋죠.

2019-01-14 11:07 UTC, nigayo commented on js/module/Carousel.js
> +    constructor({ targetHTML, intervalTime, delayTime }){
풍부한 옵션 좋아요~

2019-01-14 11:07 UTC, nigayo commented on js/module/Carousel.js
> +        prevBtn.addEventListener("click", () => {
이벤트 핸들러를 하위 함수로 분리하다보니, 깔끔해지고 좋네요.
무엇을 하는지도 잘 알겠고요.

2019-01-14 11:07 UTC, nigayo commented on js/module/ajax.js
> +        return new Promise((resolve, reject) => {
오 Promise 패턴!! 
깊게 공부하고 넘어가면 더 좋을 듯 ^^

2019-01-14 11:07 UTC, merged