[리오] Amazon 2 : plans 레이어 - STEP 1
code-squad/javascript-amazon pull request #3
Opened 2018-10-14 15:16 UTC by feanar729

Amazon 2 / STEP1 PR 보냅니다 
리뷰 부탁드립니다.

2018-10-15 03:33 UTC, nigayo commented
오후에 데모 좀 보여주세요~

2018-10-15 03:41 UTC, crongro requested changes
css/html 정말 수고많았네요.
css px단위들이 어떤규칙성이 잘 안보여요. 궁금해서 같이 한번 봤으면 하고요.

javascript코드는 리뷰남긴 것 반영해보시고요~!

2018-10-15 03:41 UTC, nigayo commented on body.css
> +  font-size: 28px;
font-size는 em또는 rem이 더 선호되고 추세.
rem이 최상위 기준점에 따라서 동작된다고 생각해서 더 추천받고 있고요.
브라우저 지원범위는 조심스럽게 접근하는 시기고요.

2018-10-15 03:41 UTC, nigayo commented on body.css
> +  padding: 0 70px 48px 70px;
48px.. 이렇게 떨어지는 게 뭔가 이유가 있을거 같은데요. 본인은 알겠죠?

2018-10-15 03:41 UTC, nigayo commented on body.css
> +  font-size: 18px;
font-size의 크기만 보면, 
너무 제각각인데요. 
기준이 있을까요?

font-size의 가이드를 정하시고,
var와 같은 css 함수를 한번 도입하는걸 해볼래요?

2018-10-15 03:41 UTC, nigayo commented on header.css
> +  width: 1905px;
왜 1905? 죠? 
일반적이지 않은 크기라서 궁금.

2018-10-15 03:41 UTC, nigayo commented on hidden-header-plans.css
> +#hidden-plans {
영역별로 css파일을 분리한건가요? 잘하셨음.

2018-10-15 03:41 UTC, nigayo commented on hidden-header-plans.css
> +  z-index: 9;
z-index가 왜 9일까요? 
마음속으로 9가 가진 의미가 무엇인지 알고 있으시죠?

2018-10-15 03:41 UTC, nigayo commented on hidden-header-plans.css
> +  left: 41%;
여기서만 %단위를 쓴 이유도 궁금하네요. 
단위도 일관된 방법으로 사용하면 더 좋죠.

2018-10-15 03:41 UTC, nigayo commented on hidden-header-plans.css
> +  background-color: #eeeeee;
반복적인것은 단축표기법.

2018-10-15 03:41 UTC, nigayo commented on prime_main.html
> +    document.addEventListener("scroll", function () {
javascript 코드는 별도 파일로 분리해서 선언하세요~ 
external 방식으로.

2018-10-15 03:41 UTC, nigayo commented on prime_main.html
> +      (ypos > 300) ? hiddenLayer.style.display = "block": hiddenLayer.style.display = "none";
300이라는 값은어디서 나온것인지 궁금..

2018-10-15 03:41 UTC, nigayo commented on prime_main.html
> +    let expandLayer = document.querySelector(".expand-membership-card");
이부분이 어떠한 함수안에 있지 않은데요.
javascript코드 모두 es6 class 로 만들어서 구현하면 좋겠습니다.

2018-10-15 03:41 UTC, nigayo commented on prime_main.html
> +        hiddenContents.style.height = "650px";
650px이 무슨 의미인지 변수로 저장하고 사용하기.

2018-10-15 03:41 UTC, nigayo commented on prime_main.html
> +    otherCloseButton.addEventListener("click", function () {
콜백은 화살표함수로 표현해보기.

2018-10-15 03:41 UTC, nigayo commented on prime_main.html
> +        hiddenContents.style.height = "0";
위에 코드와 아래 코드는 중복인듯. 
함수로 중복제거하기.

2018-10-17 03:13 UTC, feanar729 commented
refactoring 진행 되었습니다
- font-size는 body.css에서 rem을 적용시커 보았습니다
- DOM event 기능에서 classList로 사용해 refactoring 진행해 보았습니다
- CSS Layout에서 %는 hidden contents 영역에 최상단 element에서만 적용시켜 보았습니다 %로 사용하고 싶기도 했고 px 단위로 하면 고정 넓이 값으로 지정되는 점이 신경쓰여서 그랬습니다(전체적으로 다하고 싶긴했지만 그러려면 시간이... ㅎㅎ;;)
리뷰 부탁드립니다!

2018-10-17 06:58 UTC, crongro requested changes
조금 더 수정해보세요~
class는  eventhandler 라는 일반적인  기능을 포함하지 말고, 
서비스의 의미를 담는 UI요소로 만드는 게 좀더 나을 듯.

2018-10-17 06:58 UTC, nigayo commented on body.css
> +  font-size: 1.125rem;
네 em/rem 이해하셨기를~

2018-10-17 06:58 UTC, nigayo commented on event.js
> +      const displayStandard = 300;
이런값이 고정된건가요? 그렇지 않다면 함수의 인자로 받기.

2018-10-17 06:58 UTC, nigayo commented on event.js
> +      (yPos > displayStandard) ? hiddenLayer.style.display = "block": hiddenLayer.style.display = "none";
참고로 이것도 classlist를 활용할 수 있을거 같고요.
또는 show/hide 함수를 만들어도 좋을 듯.
? show() : hide();

이런식으로 동작하는.

2018-10-17 06:58 UTC, nigayo commented on event.js
> +        hiddenLayer.classList.add("trans-show-hidden");
혹시 이 부분이 toggle() 함수로는 처리 안될지 고민해볼래요?

2018-10-17 06:58 UTC, nigayo commented on event.js
> +    let expandLayer = document.querySelector(".expand-membership-card");
왜 const를 안쓰죠?

2018-10-17 06:58 UTC, nigayo commented on event.js
> +export default class HiddenContentsHandler {
class이름과 구성은, 기능단위가 아니라 의미를 담도록 해볼래요? 

class TopMenu() {

}

2018-10-17 07:24 UTC, feanar729 commented on event.js
> +      const displayStandard = 300;
함수의 인자 왜 사용하는지 / 어떻게 할지 알겠습니다.

2018-10-17 07:24 UTC, feanar729 commented on event.js
> +      (yPos > displayStandard) ? hiddenLayer.style.display = "block": hiddenLayer.style.display = "none";
넵 이런식으로 다시 해보도록 하겠습니다.

2018-10-17 07:24 UTC, feanar729 commented on event.js
> +    let expandLayer = document.querySelector(".expand-membership-card");
음;;; 요건 일부러 안쓰려는건 아니였고 미처 생각하지 못했습니다;;

2018-10-17 07:24 UTC, feanar729 commented on event.js
> +export default class HiddenContentsHandler {
기능보단 의미 기억하겠습니다

2018-10-18 08:35 UTC, closed without merging