Amazon1.Step4-Carousel
code-squad/javascript-amazon pull request #32
Opened 2019-01-28 03:38 UTC by HTMLhead

* 피드백반영 사항 
1. css함수 calc를 사용해 보려했는데 실패했습니다.. 쓸만한 곳을 찾아내기가 힘들더군요. 다른 곳에 사용해 볼 계획입니다.
2.  contentLoader.js와 topLayer.js는 합쳐서 어떤역할을 한다고 하신 말씀을 보고 여러가지로 생각해 보았습니다. 이벤트리스터에 들어가는 'contentLoaded'를 topLayer.js(지금은 scrollEvent-Sticky.js)파일 내부에 써볼까 생각했는데, 어짜피 나머지 js파일에도 contentLoaded가 들어가니까 contentLoader(지금은 app.js)에 한번에 모두 사용하는게 낫지않나 하는 생각에 이렇게 짜보았습니다.
3. entry point인 contentLoader.js 의 이름을 app.js 로 변경하였습니다. 이것이 더 entry point에 적합한 이름이라고 생각했습니다. 또한, 더 커지는 것을 방지하고, app.js 파일에는 어떤 일들이 벌어지는지만 간단히 명시하는 것이 좋다고 했던 토르코의 말이 기억나서 그렇게 해보려고 노력했습니다.

* 코드맥락
1. topLayer.js와 contentloader.js파일의 이름을 변경했습니다.(scrollEvent-Sticky.js, app.js)
1. module.js 파일을 만들어서 querySelector 와 ajax데이터를 가져오는 것을 조금 더 수월하게 할 수 있도록 만들어 보았습니다. 만들어놓은 class의 인자로 사용하도록 만들었는데, 이런식으로 사용하는게 맞는지 의구심이 들었습니다.
1. scrollEvent-Sticky.js파일에 intersectionObserver api를 사용해 보았습니다. yoon의 블로그를 참조하였습니다. 인자로 받은 header가 화면에서 사라지면 topLayer가 내려오고, 나타나면 다시 들어가도록 구현하였습니다.
1. 헤더말고도 body부분의 모든 css를 flex로 수정해보았습니다. 
1. 캐로샐 맥락
       1. 모든 이미지들이 들어가는 틀을 만들고 그 내부에 index0, 1, 2를 사용해서 배경이미지를 넣었습니다.
       2. ajax데이터로 배경이미지의 배열을 받아 만들고 그 배열의 값을 넣고 빼고 하며 무한으로 동작되도록 만들었습니다.
       3. 버튼의 방향으로 움직이는 애니메이션을 만들고 그 애니메이션이 끝나면 다시 원래대로 돌아오도록 만들었습니다. 하지만 배경이미지는 모두 바뀌어서 보기엔 오른쪽으로 넘어간 것처럼 느껴지도록 만들었습니다.
       4. 또한 애니메이션이 끝날 때 까지 버튼을 눌러도 동작되지 않도록 playBool을 추가하였습니다.
       5. 자동으로 동작되도록 하는 함수에는 setInterval을 사용하였습니다.
       6. 이미지를 모두 담아두고 있는 큰 틀에 mouseover와 mouseout이벤트를 등록하여 마우스가 큰 틀에 들어와 있을 때에는 동작하지 않도록 구현하였습니다.
       7. 이 동작을 하는 도중에는 mouseAuto 함수가 실행이 되는데, 여기에 isMouseOver불리언 값을 만들어서 만약 마우스가 안에 들어와 잇으면 자동으로 넘어가는 함수가 동작되지 않도록 만들었습니다.
1. init함수는 eventLister가 등록되는 함수들을 모아두고, domContent가 완료되었을 때 자동적으로 실행되어야 하는 동작들이 있는 함수는 constructor내부에서 실행되도록 구현하였습니다.

예제 페이지입니다.
[예제페이지](https://htmlhead.github.io/javascript-amazon/)

2019-01-28 08:25 UTC, crongro commented
제눈에는 슬라이딩 영역이 좌우측에 부분까지 일부분 보이고, 이부분이 슬라이딩 액션 이후에, 좀 늦게 로딩되서 보이는데,
버그 같습니다.
이부분수정할 수 있을까요?

2019-01-28 08:36 UTC, crongro requested changes
네 수고했어요, 
처음 UI개발이 좀 어려운데, 잘 고비를 넘고 있어요.
전체적으로 방향을 잘 잡아서 하고 잇네요.

몇개 리뷰남기부분 확인해서 수정해보세요.

기능완성도에서는 슬라이딩 될때 주변영역이 늦게 로딩되는 부분이아쉽고요.
그리고 슬라이딩방향이 일반적인 방향(좌/우 누를때 영역이동)인지 한번 다른 웹사이트와 비교해보세요,.

2019-01-28 08:36 UTC, nigayo commented on amazonJS/app.js
> +    false,
뭐가 false인지 알수가 없으니, 단일객체로 인자를 넣어주면 좋을 듯.
new Carousel_middle( {
  isGo : false,  listEl : document.querySelector(".middle-body-carousel-list')
});

이런식

2019-01-28 08:36 UTC, nigayo commented on amazonJS/app.js
> +import { Module } from "./module.js"
Module이라는 이름은 너무 일반적인 이름이라 안쓰는 게 좋을 듯.

2019-01-28 08:36 UTC, nigayo commented on amazonJS/carousel-middle.js
> +    this.module.getAjax(this.handler.bind(this), `./jsonData/data.json`);
url도 옵션으로 볼 수 있을텐데요.
Carousel_middle 클래스 생성할때 주입받는 게 더 좋을 듯.
(클래스 재사용측면에서요)

2019-01-28 08:36 UTC, nigayo commented on amazonJS/carousel-middle.js
> +      this.parsedArr.push(parsedObj["backgroundUrl"][i]);
배열을 순회하면서 push하는 거면 map을 쓸 수 있는것인지 검토바람.

2019-01-28 08:36 UTC, nigayo commented on amazonJS/carousel-middle.js
> +    this.container.style.transform = "translateX(230px)";
230px이런 하드코딩된 정보입력은 자제..이것도 계산에 의해서 뽑거나 함수나 클래스의 옵션으로 받거나.

2019-01-28 08:36 UTC, nigayo commented on amazonJS/carousel-middle.js
> +    this.container.style.transition = "all 0.5s";
all 0.5s 이런정보가 반복적인것이고, 변경이 되면 여기저기서 수정할 확률이 높음으로..
해결해보세요. ㅎ

2019-01-28 08:36 UTC, nigayo commented on amazonJS/module.js
> +class Module {
Module보다는 유용한 모음이면, 
util이 좀더 어울리는 이름일 듯.

2019-01-28 08:36 UTC, nigayo commented on amazonJS/scrollEvent-Sticky.js
> +    const io = new IntersectionObserver(entries => {
이건 질문 또는 고민꺼리인데요.
IntersectionObserver 가 지원하지 않는 브라우저에서는 어떻게동작될까요? 
브라우저 지원이 부족하다면 어떻게 하는게 좋을까요? 
(polyfill ?? 이런것이 해결책이 될지도...)

2019-01-30 03:09 UTC, HTMLhead commented on amazonJS/scrollEvent-Sticky.js
> +    const io = new IntersectionObserver(entries => {
사파리에서 동작시키니까 아예 동작하질 않더라구요. 발견하지 못했다면서 에러를 발생시키고, flex도 잘 먹지 않는것 같구요....
오픈소스에 있는 polyfill을 가져와서 script태그에 넣어서 사용해 보았더니 intersectionObserver 이벤트는 잘 실행이 되더군요.
근데 이렇게 script를 하나 더 추가하면 이 script파일을 읽으면서 시간이 더 오래걸리지 않을까 이런 생각이 들었습니다. 현업에서 polyfill을 가져와서 이렇게 쓰기도 하나요? 그리고 그 polyfill에서 필요한 기능만 사용할 수 있도록 수정도 하는지 궁금합니다.

2019-01-30 06:38 UTC, HTMLhead commented
버그를 수정하였습니다.
1. 가리개의 크기와 overFlow : hidden을 좀더 적절히 이용해서 일부분이 보이는 부분을 수정하였습니다.
1. 슬라이딩 될때 주변영역이 늦게 로딩 된다는 부분이 어느부분인지를 몰라서 제대로 수정을 못했습니다만.. 이미지를 wp대로 가리면 자연스레 해결되는 문제일것 같아서 그렇게 하였습니다.
1. 슬라이딩의 방향을 일반적으로 바꾸었습니다…ㅎㅎㅎㅎ 섬세함이 부족 했네요.

피드백해주신 부분을 반영해 보았습니다.
1. 단일객체로 인자를 넣었습니다.
1. module파일의 이름을 util로 수정하였습니다.
1. url또한 옵션으로 받을 수 있도록 작성하였습니다.
1. for문을 map으로 변경하였습니다.
1. 매직넘버들을 모두 단일객체를 사용한 인자로 받을 수 있도록 만들었습니다.
1. intersectionObserver의 polyfill을 script파일로 추가하였습니다.

나머지 개인적으로 마음에 들지 않는 부분을 수정하였습니다.
1. setInterval대신 재귀적 setTimeout을 사용하였습니다.
1. Json데이터에 주소를 가져오도록 수정하고, carousel container내부에 a태그를 넣어서 이미지가 바뀔 때 마다 주소 또한 바뀌도록 하는 이벤트를 추가했습니다.

피드백 부탁드립니다!!:sos:

2019-01-31 01:15 UTC, crongro requested changes
수정잘 봤어요.
메서드 이름이 어느덧 동사+명사가 아니고, 애매한상태에요.
의도를 잘 드러내게 전체 메서드를 모두 수정해보세요.

그밖의 리뷰도 참고해주세요.

(화 이 팅)

2019-01-31 01:15 UTC, crongro commented on amazonCss/app.css
> +@import url('./topLayer.css');
저도 이걸 잘 안 쓰긴하는데요.
성능적인 문제로 보통 안티패턴이라고 하긴해요. 참고해두세요.

https://www.keycdn.com/blog/css-performance

2019-01-31 01:15 UTC, crongro commented on amazonCss/mainCarousel.css
> +  color: var(--color-basic);
var 잘 쓰고 있음~

2019-01-31 01:15 UTC, crongro commented on amazonJS/app.js
> +document.addEventListener("DOMContentLoaded", () => {
여기 이벤트핸들러가 길어졌네요. 지금은 괜찮고요.
좀더 길어지면 별도 함수로 분리하는 것도 생각하세요.

2019-01-31 01:15 UTC, crongro commented on amazonJS/app.js
> +  const carousel_middle = new Carousel_middle({
이렇게 풍부한 옵션을 기반으로 객체를 만드는 것은 범용성을 늘리는 것이라 아주 좋아요.

참고로, 여기 아래 options 을 기반으로 객체생성하는 거 보면 무척길죠~
https://github.com/nhnent/tui.tree/blob/production/docs/getting-started.md

2019-01-31 01:15 UTC, crongro commented on amazonJS/carousel-middle.js
> +    this.length = optionObj.movingLength;
좀더 구체적인 이름...필요.
this.length 가 무엇일지..

2019-01-31 01:15 UTC, crongro commented on amazonJS/carousel-middle.js
> +    this.jsonUrl = urlObj.jsonUrl;
json도 포맷에 대한 정의라서 이름으로 부적절.
의도와 맥락을 이름에서 드러내세요.

2019-01-31 01:15 UTC, crongro commented on amazonJS/carousel-middle.js
> +    this.linkUrlArr = linkUrlArr.map(v => v);
이부분은 뭐에요? 
this.linkUrlArr = linkUrlArr;
이거랑 뭐가 다른지?

2019-01-31 01:15 UTC, crongro commented on amazonJS/carousel-middle.js
> +    this.imgUrlArr.push(this.imgUrlArr.shift());
배열조작을 해서 만드는게 좀 특이해보여요 ㅎ
괜찮습니다.

2019-01-31 01:15 UTC, crongro commented on amazonJS/carousel-middle.js
> +  initLink() {
이 함수가 linkUrlArr[1] 이값을 인자로 받으면 어떨까요? 
테스트용이한 코드에 대해서 고민해보세요.

2019-01-31 01:15 UTC, crongro commented on amazonJS/carousel-middle.js
> +    setTimeout(this.moveAuto.bind(this), 3000);
3000  이런코드를 하드코딩하지 말고, 미리 선언해두고 그것을 사용하도록 하세요.

2019-01-31 01:15 UTC, nigayo commented on amazonJS/util.js
> +  return document.querySelector(value);
querySelector 는 사실 document를 기준으로만 동작하는 건 아니죠.

div.querySelector.. 
이렇게 구현하면 기준점이 document라는 root노드가 아니라서 DOM 탐색이 좀더 빠르겠죠.

2019-01-31 01:15 UTC, nigayo commented on amazonJS/carousel-middle.js
> +    this.playBool = false;
bPlay 라는 이름이 나을 듯.

2019-01-31 01:15 UTC, nigayo commented on amazonJS/carousel-middle.js
> +    if (this.isMouseOver) {
is는 동사니까 함수에쓰시고요.
b는 boolean 타입을 말해주니까
this.bMouseOver 가 더 좋을 듯.

2019-01-31 02:13 UTC, HTMLhead commented on amazonJS/carousel-middle.js
> +    this.linkUrlArr = linkUrlArr.map(v => v);
배열을 참조하도록 만드는게 아니라 새로 만들고 싶었는데 굳이 새로 만들 필요가 전혀 없었네요....ㅠㅠ 수정하겠습니다

2019-01-31 08:43 UTC, HTMLhead commented
* 피드백 주신 부분들을 수정해 보았습니다.
1. 크롱이 말씀해 주신 변수들이 모두 적합한것 같아서 그렇게 수정하였습니다.
1. 인자로 받아야 할 값들을 받고, 인자의 이름 또한 보자마자 어떤것을 뜻하는지 알 수 있도록 수정하려고 노력했습니다
1. css를 scss파일로 변경해보았습니다. 
scss의 문법은 하나도 쓰지 않았고, 그냥 한개의 app.css에 모든 css파일을 컴파일 해주고 싶어서 사용했습니다. 다음 스텝부터 찬찬히 scss에대해 공부해가며 하나씩 고쳐나갈 계획입니다.

피드백 부탁드립니다! 🆘

2019-02-07 06:55 UTC, crongro approved these changes
잘 수정하셨어요.

scss는 좀더 공부해서 mixin이나 다양한 장점을 적용해보면 더 좋겠어요.

다음 미션 하셔도 될거 같아요. 

이번 미션 구현한 방식이 좀 특별한데요.
다른 사람이 애니메이션 어떻게 구현했는지 한번 물어서 이해해보세요.

2019-02-07 06:55 UTC, nigayo commented on amazonJS/carousel-middle.js
> +    this.container = qs(document, elObj.container);
constructor 에 값을 할당할때 Object.assign을 사용할 수 있어요.
이패턴이 편리해서 꽤 쓰이니 알아두세요.

2019-02-07 06:55 UTC, nigayo commented on amazonJS/scrollEvent-Sticky.js
> +    this.hiddenLayer = qs(document, elObj.hiddenLayer);
이 코드보니 생각난건데요.
qs가 default parameter를 사용하면서 동작하게 할 수도 있을듯.(기본값은 document)

2019-02-07 06:55 UTC, nigayo commented on amazonScss/topBody.scss
> +  height:396px;
다음 css 개발에서는 em/rem 중 하나를 골라서 사용해보세요.

2019-02-07 06:55 UTC, merged