[Torce]Step5 - Autocomplete
code-squad/javascript-amazon pull request #33
Opened 2019-01-28 06:56 UTC by cohily12

PR이 늦었습니다.
- 스텝4에서 주신 리뷰 사항 수정, 반영하였습니다.
- 클린코드 작성이 쉽지 않네요...
- 부분적으로 fetch, async/await를 사용해보았습니다. 좀 더 깊게 공부할 필요가 있을 거 같습니다.
- 자동검색 기능 구현 외 dimmed 구현, keyevent 구현의 로직 순서가 맞는 지 궁금합니다.

* 배운 점
- 넥스트캠프에 나와있는 acapi url이 http로 되어있어 데모 페이지의 https에서 로드 되지 않는 mixed content에 대해 알 수 있었습니다.
- form tag에 대해 공부할 수 있는 시간이었습니다.

보시고 많은 리뷰 부탁드립니다~~

[데모](https://cohily12.github.io/javascript-amazon)

2019-01-28 08:57 UTC, crongro requested changes
수고했어요.
점점 감을 찾고 계십니다.

큰문제는 없고 잘 구현했어요.

리뷰 남긴거 조금 더 수정하고 가면 좋겠어요.

2019-01-28 08:57 UTC, nigayo commented on js/app.js
> +const musicCarousel = new Carousel("#music-card", {
carousel 옵션으로 동작하는 거 좋고요. 객체를 활용하는 것도 좋습니다.

2019-01-28 08:57 UTC, nigayo commented on js/app.js
>  window.addEventListener("load", () => {
DOMContentloaded만으로도 동작할수 있는 거 같아요.
두 개의 대표적인 차이는 DOMC..이 더 빨리 발생하는 이벤트라는 점이죠.
그러니 DOMC..  이벤트를 활용해도 되는거면 DOMCon..을 사용하세요.

2019-01-28 08:57 UTC, nigayo commented on js/init.js
> +network.get(`${URL.SERVER}json/musicCarousel.json`)
init.js 는 애매합니다.
init이 필요한 원래의 클래스( 자동완성이나 캐로셀 등)에서 하면 될 일 같아요.

2019-01-28 08:57 UTC, nigayo commented on js/module/Autocomplete.js
> +import { URL } from "../config.js"
참고.
webpack이라는 로더 툴을 사용하면 더 많은 종류의 것들마저 이런방식으로 동작시킬 수가 있어요.
image 나 css 로더가 대표적인데요. 그런 예제를 한번 찾아보고 구경해보세요.
물론 그것이 js표준은 아니라 변환해서 쓰게 되는 것이고요(webpack이 의존관계를 분석해서 bundle파일을 만들어주고 이것을 배포)

2019-01-28 08:57 UTC, nigayo commented on js/module/Autocomplete.js
> +            this.dimmer.off();
this.dimmer.off();
 이런 메서드 이름 간결하고 명확해서 좋아요.

2019-01-28 08:57 UTC, nigayo commented on js/module/Autocomplete.js
> +        keywordJson
여기서 then/then 하고 있는데 async await로 바꿀 수 있어보이네요.

2019-01-28 08:57 UTC, nigayo commented on js/module/Autocomplete.js
> +        this.searchEl.addEventListener("keydown", (evt) => {
이벤트리스너(핸들러)를 별도의 함수선언으로 분리하는 것을 추천합니다.
그래야 핸들러만 따로 테스트하기도 쉽고요(테스트코드 구현 용이성)

2019-01-28 08:57 UTC, nigayo commented on js/util.js
> +export function $(selector, root = document) {
굿

2019-01-28 08:57 UTC, nigayo commented on js/module/Autocomplete.js
> +            if(!this.debouncer) this.debouncer = debounce(this.showKeywords.bind(this), 500);
500이런 매직넘버는 늘 없애도록 노력해주세요~

2019-01-28 08:57 UTC, nigayo commented on js/module/Autocomplete.js
> +class Autocomplete {
클래스 전체 형태가 좋아요.
이런식으로 개발하면 됩니다.

2019-01-28 08:57 UTC, nigayo commented on js/module/Autocomplete.js
> +            else if(evt.keyCode === 40) {
별건아닌데 40이 무슨키인지 모를 수 있음으로, 객체에 매핑데이터를 만들어서 써도 좋을 듯.

2019-01-31 07:59 UTC, cohily12 commented
리뷰주신 사항 반영하여 수정하였습니다.

2019-02-07 06:42 UTC, crongro approved these changes
코드를 이제 잘 짜네요.
💯

2019-02-07 06:42 UTC, nigayo commented on js/app.js
> +    const musicCarousel = new Carousel(".music-carousel", {
Carousel 컴포넌트가 범용적으로 동작하는 거 같아서 좋아보이네요.

참고로, 라이브러리 만들어서 NPM 프로젝트로 등록하는 거 해보면 재미있을거에요.
좋은 경험일겁니다.

2019-02-07 06:42 UTC, nigayo commented on js/app.js
> +        bDimmer: true
옵션중에는 함수도 넣을수도 있으니 참고하세요.
 const autocomplete = new Autocomplete(".nav-input-bar", {
"AFTER_RENDER" : ()=> {....}, 
 ...
}

2019-02-07 06:42 UTC, nigayo commented on js/config.js
> +export const URL = {
config 뺀거 잘했네요.

2019-02-07 06:42 UTC, nigayo commented on js/module/Autocomplete.js
> +    async requestSuggestions(){
async함수 잘 썼네요.
비동기 호출이 한번뿐이라 장점을 느끼긴 어렵지만, 사용법을 익힐겸 잘 했어요

2019-02-07 06:42 UTC, nigayo commented on js/module/Autocomplete.js
> +            arrowUp: 38,
대문자로 주로 쓰겠죠.
key = {
ARROW_UP : 38, ...
}

2019-02-07 06:42 UTC, merged