Step3 PR
code-squad/javascript-amazon pull request #34
Opened 2019-01-29 13:08 UTC by KaKaFE

Step3 PR 입니다.
commit을 거의 못했습니다... 다음 스텝 에선 의식하고 하겠습니다.
transition 을 이용해서 plans 레이어를 구현하였고
JS 는 class를 이용해서 만들 었습니다....코드가 깔끔 하지 못한 것 같습니다 ㅠㅠ 
많은 피드백 부탁드립니다...

demo : https://kakafe.github.io/amazoncopy/

2019-01-30 01:59 UTC, nigayo commented
데모 잘 봤어요~ 

커밋로그는 습관들이기 어렵긴해요. 그래도 계속 의식해보시고요.

코드가 깔끔하지 못하는 것에 너무 의식하지 마시고,  나중에 어떻게 개선하면 되겠군. 이런생각 정도 하셔도 좋아요.
좋은코드는 정답도 끝도 없어서.. 너무 고민에 빠지면 힘들어요.

2019-01-30 02:10 UTC, crongro requested changes
수고하셨어요. 👍 

전체 구조와 이벤트, DOM이해등이 괜찮아 보여요.

리뷰남겨드린 거 한번 수정하고 해보시죠.

2019-01-30 02:10 UTC, crongro commented on CSS/main.css
> +* {
css역시 공통 부분을 이렇게 분리하는 건 좋습니다.

2019-01-30 02:10 UTC, nigayo commented on CSS/nav-planpage.css
> +.planpage {
이름이 어느정도 함축적이여도 좋아요.
너무 길면 가독성이 오히려 떨어져서... 
예를들어 planpage보다는 plan 이라고 해도 뭔지 알거 같네요.

2019-01-30 02:10 UTC, nigayo commented on JS/nav.js
> +class Nav_Elements {
네이밍에, 
카멜표기법과 (_)를 혼용할 필요는 없을 듯.

2019-01-30 02:10 UTC, nigayo commented on JS/nav.js
> +    this.moreCntArrow.addEventListener("click", this.removeClass.bind(this));
arrow function을 쓰면 지금 bind가 필요없죠? 왜 그런지도 알고 계시면 좋고요.

2019-01-30 02:10 UTC, nigayo commented on JS/nav.js
> +    this.planPage = document.querySelector(".planpage");
constructor에  너무 많은 this property가 없으면 좋겠어요.
변수(상태)는 유효범위를 좁히는 게 중요한데요.  
class property보다는 각 메서드의 지역변수로 옮길 수 있으면 옮기도록 하세요.

2019-01-30 02:10 UTC, nigayo commented on JS/nav.js
> +    this.removeClassList(this.planPage, "planpage-more-click");
planpage-more-click이런 정보를 객체로 만들어서 쓰는 건 어때요?

const CLASS_MAP = {  "more" : "planpage-more-click",....}

2019-01-30 02:10 UTC, nigayo commented on JS/nav.js
> +NavElements.addScrollEvent();
이 세줄을 밖에서 해도 되는데요.
그것보단,  Nav_Elements  클래스 안에서 initialize() 메서드 같은거 만들어서 모아두고, 

이부분에서는 NavElements.initialize()  메서드를 호출하는 건 어때요?

2019-01-30 03:29 UTC, KaKaFE commented on JS/nav.js
> +    this.moreCntArrow.addEventListener("click", this.removeClass.bind(this));
처음에는 arrow function을 사용해서 구현했는데, addEventListener 내부 코드가 길어져서 따로 빼서 bind를 했는데, arrow function을 활용하는 다른 방법이 있을까요?? 궁금합니다~!

2019-01-30 03:36 UTC, KaKaFE commented
리뷰 주신 사항 수정하였습니다!
-질문
리뷰 주신 것 중에, class map 객체를 통해서, 맵핑 하는 방식을 구현할때,
navElements 클래스 안에 프로 퍼티로 넣자니 접근 할때  navElements .classMap.more  이렇게 
길어질거 같아서, 전역변수로 만들었는데요,  어떤게 더나은 방법인지 궁금합니다

2019-01-31 00:34 UTC, nigayo commented on JS/nav.js
> +    this.moreCntArrow.addEventListener("click", this.removeClass.bind(this));
bind를 해도 돼요. arrow함수를 쓸수도 있다는 것이고요.
arrow function을 쓰면 왜 bind를 안해도 되는지를 이해하셔야하고요.

```javascrit
this.moreCntBtn.addEventListener("click", (e)   => this.removeClass(e));
```

2019-01-31 00:47 UTC, crongro approved these changes
네 수정확인했어요.
클래스나 메서드의 크기는 좋습니다. 이렇게 개발하시고요.
클래스를 사용해도 함수의 인자를 좀더 많이 활용하면 좋겠어요.그래야 testable  code를 만들 수 있습니다.

리뷰참고해서 다음과제 개발해보세요~

2019-01-31 00:47 UTC, nigayo commented on JS/nav.js
> +const classMap = {
classMap을 주입시키는 것도 가능할 듯. 

```javascript
const navElement = new NavElements(classMap);

...

class NavElements {
  constructor(cmap) {  //받을땐 이름을 좀 줄여써도 되고요.
    this.cmap = cmap;
    this.el.addClass(this.cmap.middleIntrc);
  }
```

그리고 ES Modules를 활용하면 classMap을 별도 파일로 분리하고, import받아서 쓸수도 있고요.

2019-01-31 00:47 UTC, nigayo commented on main.html
> +    <link rel="stylesheet" type="text/css" href="./CSS/nav-plan.css">
실무에서는 css파일도 여러개 배포하지 않고, 개발할때는 분리하지만 배포할때는 하나로 합치죠.
HTTP Request수를 줄이기 위함이에요. (로딩 성능개선의 기본)

2019-01-31 00:47 UTC, nigayo commented on JS/nav.js
> +    this.navPosition = 112;
이런값은 계산에 의해서 값을 얻거나...아니면 NavElements클래스를 초기활할때 인자로 받거나 하세요.
이렇게 하드코딩하는 건 별로에요~ 

new NavElemtns({ navPosition : 112, primBtnPosition: 465}) 이런식도 좋죠.

2019-01-31 00:47 UTC, nigayo commented on JS/nav.js
> +  removeClassList(el, className) {
이 함수가 필요없다고 생각하고요. 한줄짜리 함수라서...
더구나 클래스를 제거하는 것인데,  이름만 봐서는 classlist를 제거한다고 되어 있네요.

2019-01-31 00:47 UTC, nigayo commented on JS/nav.js
> +  initInteraction() {
Interaction인데 스펠링이 틀린 듯~

2019-01-31 00:47 UTC, nigayo commented on CSS/nav-plan.css
> +	width: 998px;
이제부터 CSS구현하실때
em이나 rem을 공부하시고요.

px이 필요한 곳(font, box-model)에 rem을 사용해보세요~

2019-01-31 00:47 UTC, merged