[Jin & Gren] Step12-1
code-squad/javascript-amazon pull request #57
Opened 2019-06-20 08:22 UTC by fed-gren

- 애니메이션 구현
- 클래스 분리(Navigation, Carousel)

위 사항 구현했습니다. 리뷰 부탁드립니다.
[동작 확인](https://fed-gren.github.io/amazone-carousel/)

2019-06-20 09:01 UTC, crongro requested changes
동작은 매우 잘 되는거 같아요.

객체를 나눈 방법에서, 많은 고민이 느껴지네요. 
나름대로의  방법을 연구한 거 같아서 좋고요.

한가지 제안을 하자면, controller를 다른 클래스에 주지 말고, 
controller 클래스가 다른 두 개의 객체를  받아서 동작하도록 하는 건 어떨까 싶네요.
물론 본인들이 참고해서  수정방향을 결정하시고요.

컨트롤러를 만들어서 이미 어려운 길을 가게 됐지만, ㅎㅎ
조금더 고민해보면 좋겠어요.

2019-06-20 09:01 UTC, crongro commented on app.js
> +import Jungle from "./Jungle.js";
Jungle와 app.js를 하나로 합쳐도 될 거 같아요.
Jungle 이 메서드 두개 있는 클래스라, 재사용되는 것도 아니기도 하고요.

2019-06-20 09:01 UTC, crongro commented on Jungle.js
> +    const navigation = new Navigation(classes);
classes 라고 하니, css class인지 javascript class인지 헷갈리는군요.
option이라고 해도 될거 같고요. elementObject라고 해도 되고요 등등..

2019-06-20 09:01 UTC, crongro commented on components/controller.js
> +  regist(fn) {
register 라는 풀네임을 쓰는 게 좋겠죠.

2019-06-20 09:01 UTC, crongro commented on components/Carousel.js
> +    controller.carousel.regist(this.move.bind(this));
초기화 단계에서 왜 controller에 move함수를 등록하지? 라는 의문이 들어요.
즉 의도가 잘 드러나지 않는 코드라고 생각됩니다.

무엇을 하기 위함인지 어느정도 의도가 드러나면 더 좋겠어요.

2019-06-20 09:01 UTC, crongro commented on components/Carousel.js
> +      controller.carousel.sendId(id);
이 부분은 좀 의도가 보이고요. 
id를 보내는 구나. 누군가 쓰겠지 라고요.

2019-06-21 09:48 UTC, fed-gren commented
@nigayo 
리뷰 해주신 내용 토대로 수정 완료했습니다.

- 옵저버 패턴 적용
  - 수정 이전에는 옵저버 패턴을 따로 공부하지 않고 같이 고민해서 구현했는데, 리뷰 해주신 후 수정한 코드는 옵저버 패턴을 공부 후 적용했습니다.
- Jungle이라는 amazon ui 라이브러리 구현
  - [이전 피드백](https://github.com/code-squad/javascript-amazon/pull/57#discussion_r295695335) 내용은 의도한 게 있었습니다.
Jungle이라는 라이브러리를 사용자가 app.js에서 import해서 사용하는 방식을 가정하고 구현했었습니다. 
  - 리뷰 후 수정하면서 라이브러리 구조를 다른 UI가  쉽게 추가될 수 있도록 변경했습니다.

2019-06-21 09:51 UTC, eugene94 commented
[동작구현](https://fed-gren.github.io/amazone-carousel/) 링크입니다.

2019-06-24 05:51 UTC, crongro approved these changes
옵서버 잘 봤어요~ 
지금 구현한 방식은 사실상의 표준처럼 사용할 수 있는 옵서버패턴 코드네요.
보통 모델이 발생하고, 뷰가 구독하고 그런것이 일반적이더군요.
하지만 UI의 복잡한 상황에서는 뷰가 발생하고 다른 뷰가 구독하기도 하고,,등등 좀 복잡해질수도 있어요.
매끄러운 흐름으로 그때그때 만들어야겠죠.

2019-06-24 05:51 UTC, nigayo commented on Jungle/Observer.js
> +    this.handlers = {};
옵저버에 담을 데이터구조는 정해진 방법은 없더라고요, 
객체,Map,배열등 필요한 형태의 자료구조를 사용하시면 되죠. 
잘하셨어요.
🥇

2019-06-24 05:51 UTC, nigayo commented on Jungle/Observer.js
> +    this.handlers[eventName] = this.handlers[eventName].filter(
filter가 이럴때 유용하죠 잘 했음.

2019-06-24 05:51 UTC, nigayo commented on Jungle/components/Carousel.js
> +    this.itemWidth = this.cardSlider.firstElementChild.getBoundingClientRect().width;
firstElementChild 이런 속성은 DOM구조변경에 취약하기도하고, DOM구조에 의존된 코드라서 아주 바람직하진 않아요.
물론 dom구조변경이 안된다면 안전하게 사용가능하죠.

2019-06-24 05:51 UTC, nigayo commented on Jungle/components/Carousel.js
> +    return Object.assign(this.defaultConfig, config);
그냥 든 생각인데, 캐로셀처럼 여러개 컴포넌트가 증가된다면? 
다음에 검색창 만들때도 컴포넌트 방식으로 개발한다면 mergeConfig같은 함수가 중복으로 생기겠죠?
어떻게 이부분을 해결할지 다음미션에서 한번 고민해보세요.

2019-06-24 05:51 UTC, nigayo commented on Jungle/components/Carousel.js
> +    el.style.opacity = val;
opacity 속성만 할당하기에는 좀 아쉽고, 일반적인 css  속성을 설정하는 범용적인 함수를 만들어도 더 좋을거 같네요.
setCSS나 css() 이런식으로?

2019-06-24 05:51 UTC, nigayo commented on Jungle/components/Carousel.js
> +    if (this.isEndOfCards()) {
중첩된 코드니까, 하나의 if문으로 합쳐도 되겠네요.

2019-06-24 05:51 UTC, nigayo commented on Jungle/index.js
> +      observer.register("moveCarousel", nav.setItem, nav);
구독역할인 observer.register를 여기서 할 수도 있고, 
Navigation 클래스 안에서 할 수도 있을텐데요. 

장단점이 크진 않지만, 
Navigation클래스 응집도 차원에서는 그 안에서 구독하는 것을 해도 좋아보이네요.

2019-06-24 05:53 UTC, merged