[Vahn - Step2] Add basic CSS layout
code-squad/javascript-amazon pull request #6
Opened 2018-11-12 01:35 UTC by Vanary

CSS로 바탕 레이아웃을 잡았습니다. 

[개요]
- 작업하면서 CSS가 눈에 잘 안 들어와서 LESS를 사용해봤습니다.
(LESS로 작성 -> VSCode에서 저장시 CSS로 변환)
- 현재 버전은 가로 1280px 이상 화면에 최적화되어 있습니다.

[느낀점]
- 블록 안의 개체들을 정렬하는 게 (특히 세로로 정렬할 때) 어려웠습니다
- LESS로 쓸 때는 좋았는데, 변환된 CSS가 길고 텍스트가 많아서 용량이 커진 느낌이 듭니다. 아직은 minify에 대한 고민을 안 해도 괜찮을까요?

2018-11-12 02:26 UTC, crongro commented
@Vanary  less를 실무에 많이 쓰는 부분이라 이해하면 좋은데요.
css를 좀더 직접 구현하는 경험이 필요합니다.
레벨3을 할때, less의 사용은 50%넘기지 않도록 하세요.

2018-11-12 02:49 UTC, crongro requested changes
👍  잘 했어요.
less를 쓰면 안되지만 ㅋ 이미 써버렸으니 이대로 계속 해야할 듯.
less는 superset이라 css를 그대로 쓸 수도 있어요. 그러니 가급적 css 를 온전히 이해한다고 생각하고 
css방식으로 구현하려고 하세요.
아니면 less를 쓰더라도 css를 잘 이해한 상태면 상관 없습니다.

그리고 preprocess의 단점이 디버깅이 좀 어려운편이고, 결과물의 코드가 너무 커져버릴 수 있다는 점이기도 합니다.
그럼에도 개발단계에서 생산적인 방식이 가능해서 실무에선 반드시 씁니다.

디자인  가이드 라인이 없어서 단위(px,em,%등)가 약간 제각각인데요.
이런 부분이 좀더 통일되고 일정하게 맞춰주면 더 좋겠네요.

리뷰남김 부분 선택적으로 좀더 수정하고 넘어가봐요.

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +/*=============
참고로  less 보다는 sass가 좀더 많이 쓰여요~

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +@padding-left-for-banner-contents: 5vw;
vw 이런 속성들을 비롯해서 가끔 caniuse.com 등에서 브라우저 지원범위를 살펴볼 필요가 있어요.

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +    font-size: 1.1em;
em 과 rem을 혼용해서 사용하면 좀 헷갈릴 수 있어요.
보통 권장되는 건 절대기준을 잡고 수정하는 것이라 rem이 좀더 많이 쓰임.

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +                .search__category-selector{
less/sass를 사용할때 코드의 중첩된 표현이 너무 깊지 않도록 하는 게 좋아요.
5단계까지 표현하면 너무 깊은 느낌.

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +    .header__quick-links {
언더바와 하이픈이 섞여 있는 이름인데, 스스로 정한 규칙이 있는거죠? 
자칫  헷갈려 보일 수도 있을 듯 해요.

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +        & > :nth-child(1) > button{background: linear-gradient(35deg, rgb(10, 130, 210), rgb(30, 170, 180));}
linear-gradient 를 썼네요? 외울 필요는 없지만 어떻게 동작하는지 잘 이해하고 넘어가도록 하세요.

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +                height: @prime-benefits-carousel__category-button--height;
이름이 좀 길어요 ㅎ
@prime-benefits-carousel__category-button--height

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +    & > * {
& > *  
자주 사용했는데요.

'*' 는 모든 것에 다 반영되는  것이라 강력하죠. 그만큼 위험해서 잘 안쓰는게 일반적이고요.
따라서 명학한 node이름이나 class이름등으로 표현하는게 좋겠습니다.

2018-11-12 02:49 UTC, nigayo commented on css/main.less
> +            em {font-size: 1.2em; font-weight: 800;}
일관된 스타일을 반영하는게 좋은데요.
font-weight 값과 같은 값도, 
 일관되도록 변수에 담아두고 쓰는 게 어떨까 합니다.

2018-11-12 05:36 UTC, Vanary commented on css/main.less
> +    .header__quick-links {
전반적으로  클래스 이름들 정리하겠습니다.

BEM 방법론을 따라 개체(__, 언더바 두 개)와 속성(-- 하이픈 두개)을 표기하는 와중에,
개체 이름이 긴 경우에는 일반적인 css 표기법을 따라 스네이크 케이스로 표기하니 선이 여기저기 많아졌네요 (흑흑)

2018-11-13 02:24 UTC, nigayo commented on css/main.less
> +    .header__quick-links {
BEM도 솔찬히 쓰이는 방법이에요. 대부분 회사들은 자기들만의 컨벤션을 지키려고 노력은 하죠.지금은 무엇이 좋다보다 BEM처럼 어떤 방법을 따라하거나 스스로 정해서 지켜보는 경험이 중요합니다.

2018-11-19 03:02 UTC, Vanary commented
피드백 주신 내용을 포함, 아래와 같이 개선했습니다.
* pre-processor 없이 순수 CSS로 변환
* 단위 통합: rem을 기본으로, 제한적으로 %를 사용했습니다.
* 일관된 개체 서식 규칙(간격, 높이/너비, 폰트 크기)을 사용했습니다. 
  - 공통적으로 적용되는 서식값은 var()를 사용해 공유했습니다.
* 애스터리스크를 삭제하고 명확히 자녀 개체를 지정하게 수정했습니다.
* 클래스명은 BEM 방법론을 중심으로, 가독성을 위해 camelCase를 섞어 개선했습니다.

[느낀 점]
* CSS로 작성하고 중첩 구조를 풀어놓으니 서식이 더 단단해진 느낌입니다.
* 한번 써봤다는 데 의의를 두고 pre-processor는 접어두기로 했습니다.
현재 수준에서는 생산성에도 큰 차이 없는 것 같아요. 호호... 

검토 부탁드립니다 ^^~

2018-11-20 05:32 UTC, crongro approved these changes
수고했어요.
less를 안쓰고도  잘 구현했네요.
다양한 속성들이 보여서 좋고, 가이드라인에 따라서 구현해서 규칙이 있어보이는 css 코드가 됐네요.

selector에 div, a 등 element명으로 많이  탐색하는데요,  
css class도 잘 활용하도록 해보세요.
그외 selector 문법등도 더 공부하면 좋겠고요.

2018-11-20 05:32 UTC, crongro commented on README.md
> +- 글자체: Open sans
디자인 가이드라인 같군요. 잘했어요!

2018-11-20 05:32 UTC, crongro commented on README.md
> +  * 검색창: 1.2rem
꼼꼼하군요!

2018-11-20 05:32 UTC, nigayo commented on README.md
> +  * 버튼: 문자박스 높이 상하 + 0.5rem, 너비 좌우 + 2rem
디자인 없이  ..텍스트로 표현하니까 보기 어렵긴하네요.
실무에서 만약 디자인 가이드라인이 필요하면, 시각적인 UI에 표현하겟죠.

2018-11-20 05:32 UTC, nigayo commented on css/main.css
> +    --benefitsCarousel__categories--button-width: 15rem;
이름들이 좀 긴거 같은데, 본인은 어떠세요? 
이런건 실무에선 팀이 결정하기 나름인데, 절대적으로 이름이 좀 긴편입니다.

2018-11-20 05:32 UTC, nigayo commented on css/main.css
> +    transform: translate(-50%, -50%);
transform의 translate 의 특성은 잘 공부해두면 좋아요.

2018-11-20 05:32 UTC, nigayo commented on css/main.css
> +.local-banner-without-bg-img .carousel__cardSlot img {height: calc(var(--horizontal-banner-height) * 0.7);}
군데군데 calc 를 잘 활용했군요. 👍

2018-11-20 05:32 UTC, merged

2018-11-20 06:21 UTC, Vanary commented on css/main.css
> +    --benefitsCarousel__categories--button-width: 15rem;
제가 보기에도 좀 깁니다. 팀에서 미리 공유하는 영역이름이 있다면 더 짧게 썼을 것 같아요.
'혜택 카로셀' 대신 '카로셀'로만 쓰거나, '버튼'은 'btn'으로 쓰는 등.

작업하면서 좀 더 일반적이고 짧은 단어로 영역을 표현할 수 있게 고민해보겠습니다!