[Q]: Step14-1 미션 PR
code-squad/javascript-amazon pull request #73
Opened 2019-07-03 12:43 UTC by park78951

Step14-1 미션 검토 부탁드립니다.

처음에는 data를 관리하는 module과 view를 관리하는 module을 클래스로 각각 만들고 싶었지만 데이터의 변경이 없다보니 필요성이 없어져서 *View* 를 관리하는 module만 클래스로 만들었습니다.

Carousel Header(Navigator) 부분과 Main Contents 부분의 내용을 모두 template literal을 사용해서 rendering 되도록 하였으며 template literal을 만들어주는 함수를 따로 module로 빼서 View 클래스에서 호출하는 방식으로 설계했습니다.

설계하면서 새롭게 방식을 배우고 짜다보니 재밌게 짰던것 같은데, 다른 패턴들도 계속 봐야될것 같습니다.

2019-07-04 06:23 UTC, nigayo commented
'필요성이 없어져서 View 를 관리하는 module만 클래스로 만들었습니다.''

-> 스스로 판단하는 과정이 좋네요.

2019-07-04 06:37 UTC, crongro requested changes
질문이 있어서 request changes 합니다.

2019-07-04 06:37 UTC, nigayo commented on app.js
> +const getData = async () =>
getData 보다는 구체적인 이름으로 표현해야겠죠.

2019-07-04 06:37 UTC, nigayo commented on app.js
> +  localData
화면렌더링이 순차적으로 headerViewer ->  mainViewer 로 진행되는 게 맞나요? 
동시에  될 수 없는건가요?

2019-07-04 06:37 UTC, nigayo commented on src/js/helper/template.js
> +const template = {
template을 분리하는 것도 좋은 전략이죠.
지저분해서..

아니면 이런 구조도 좋고요.
/header/header.js
/header/headerTpl.js

/main/main.js
/main/mainTpl.js

이런식으로 디렉토리별로 template을 관리할 수도 있겠네요.
(참고)

2019-07-04 06:37 UTC, nigayo commented on src/js/viewer.js
> +class Viewer {
Viewer보다는  자세한  UI이름을 지어주셔야..

2019-07-04 06:54 UTC, park78951 commented on app.js
> +  localData
사실 동시에 해야할지를 고민했었는데, 크게 상관이 없는 것 같아보여 가독성이 더 낫지 않을까 라고 생각해서 순차적으로 진행되도록 코드를 작성했습니다. 말씀해주셔서 다시보니 불필요하게 then 작업이 추가되고 코드가 길어지는 것 같네요.... 변경하도록 하겠습니다.

2019-07-04 11:24 UTC, nigayo commented on app.js
> +  localData
순처적이면 작업이 느리죠. 
병렬로 처리되도록 해도 될 거 같아요.

2019-07-05 04:52 UTC, park78951 commented on app.js
> +  localData
오... 넵 피드백 감사합니다. 말씀해주신대로 변경했습니다.

2019-07-08 07:52 UTC, crongro approved these changes
머지합니다. 수고하셨어요!

2019-07-08 07:52 UTC, nigayo commented on app.js
> +      const carousel = new Carousel(config);
이렇게 되면 header와 main이 렌더링된 이후에, 
carousel이 되는 순서인데요. 이건 맞겠죠? 

순차적으로 진행되는 것이면  이렇게 구현하는게 맞겠죠.

2019-07-08 07:52 UTC, merged