[Vahn - Step3]
code-squad/javascript-amazon pull request #8
Opened 2018-11-23 01:45 UTC by Vanary

Plans 레이어를 추가했습니다. 
**[주요 변경사항]**
* HTML & CSS
  - .header 아래에 .stickyNav를 추가하고, position:sticky를 적용했습니다.
  - .header를 제외한 형제 개체들을 main 개체 안에 묶고, main 개체에 position:absolute를 적용했습니다. 
* JS
  - 요구사항을 구현하기 위한 스크롤/클릭 이벤트 리스너를 추가했습니다.
  - 2개의 개체 (검은색 bar와 펼침 레이어)와 연관된 동작을 각각 ES6 클래스로 묶었습니다.

**[궁금한 점]**
* 흐름 상 객체를 생성할 일이 없어서, 클래스는 객체를 대신해 메서드를 정리하는 용도로만 사용했습니다. 요구하신 사용법이 맞는지 궁금합니다~!

+@ 동작 확인용 [테스트 페이지](https://vanary.com/javascript-amazon/)를 마련해봤습니다. 호호

2018-11-23 05:10 UTC, nigayo commented
데모까지 바로 볼 수 있다니, 무지 좋군요.

2018-11-23 05:26 UTC, crongro requested changes
고민거리를 드리니 좀더 고민해보시고, 수정해보세요.
전체적으로 DOM/EVENT를 잘 이해하고 계시네요.
굿

2018-11-23 05:26 UTC, crongro commented on scripts/main.js
> +function setBodyHeight() {
요즘은 웹프론트엔드 개발할때 class를 사용하면,(다시말해, 객체지향으로 개발한다면) 이렇게 클래스 밖에 함수를 덩그러니 구현하는 경우는 적어요. 모두 클래스 안에 있으면 더 좋죠. 참고하세요.

2018-11-23 05:26 UTC, crongro commented on scripts/main.js
> +class PrimeDetailLayer {
지금 class를 쓸필요가 없을 수 있어요. 객체를 여러개 만드는 것이 아니니까요.
하지만, 비슷한 역할을 하는 녀석들을 모듈로 묶는 것에 좀더 의미를 둘 수 있어요.

그리고 클래스를 쓴다면 그다지 쓸모 없는 static 메서드는 필요 없고요. 
조금이라도 범용적으로 동작하면 더 좋기때문에,  PrimeDetailLayer의 경우 constructor를 만들어서 stickyBar 와 같은 것을 인자로 받는 것이 좋습니다.

2018-11-23 05:26 UTC, crongro commented on scripts/main.js
> +class StickyBar {
StickBar는 딸랑 함수 하나 가지고 있음으로 클래스의 형태를 가질필요는 없을 것 같아요.
클래스를 여러개로 나누기보다는,  연관된 일을하는 PrimeDetailLayer와 StickBar를 합치는 것도 좋겠네요.

2018-11-23 05:26 UTC, crongro commented on scripts/main.js
> +      miniBar.classList.replace("opened", "closed");
classlist를 아주 많이 쓰게 될거에요. 잘했어요.

2018-11-23 05:26 UTC, crongro commented on scripts/main.js
> +window.addEventListener("load", () => {
load와 DOMContentLoaded(더  유용하게 잘 쓰이는)의 차이를 알아두세요.

2018-11-23 05:26 UTC, crongro commented on scripts/main.js
> +window.addEventListener("load", () => {
load의 콜백함수 내용은 무엇을 하는지 함수와 메서드호출로만 구성되어 있어서 참 좋아요.

2018-11-23 05:26 UTC, crongro commented on scripts/main.js
> +window.addEventListener("scroll", StickyBar.updateVisibility);
이녀석도 load안에 넣어도 될 듯.

2018-11-23 13:18 UTC, Vanary commented
피드백 주신 내용을 아래와 같이 개선했습니다
* 기존 2 개 클래스를 하나의 StickyNav 클래스로 통합했습니다.
  - 전역공간에 있는 함수를 위 클래스 내부로 이동했습니다
  - 메서드의 static 속성을 제거하고, 클래스의 최소한의 재사용이 가능하도록 개선했습니다
* 클릭 이벤트 리스너는 빠르게 DOMContentsLoaded 이벤트 이후 적용되도록 개선했습니다.

2018-11-26 02:21 UTC, crongro approved these changes
네 리뷰가 늦었군요.
잘 수정했어요.
step4로 가시죠.

2018-11-26 02:21 UTC, crongro commented on scripts/main.js
> +const stickyPlansLayer = new StickyNav({
생성자의 인자로 객체를 넣어주는 건 좋은방법이에요. 잘했음.

2018-11-26 02:21 UTC, crongro commented on scripts/main.js
> +    const totalHeight = Array.from(body.children).reduce((acc, el) => {
참고로, array .from 대신 spread operator 도 쓸 수 있죠.

2018-11-26 02:21 UTC, crongro commented on scripts/main.js
> +      event.preventDefault();
보통 preventDefault는 이벤트리스트함수 위쪽에서 호출해서, 기본이벤트동작을 막아요.

2018-11-26 02:21 UTC, merged