Koon : Step14-2 & Step15-1 미션 제출합니다!
code-squad/javascript-amazon pull request #93
Opened 2019-07-20 09:00 UTC by kkw10

1. step14-1 : 리뷰 내용 반영
2. step14-2 : event delegation 적용
3. step15-1 : 미션 요구조건을 만족하는 검색 app 구현

* 실수를 해서 커밋이 다 날라가버렸습니다 ㅠㅠ
* 검색 가능 키워드는 'html', 'css', 'javascript'입니다.
*  300ms지연 부분을 제외한 기능 구현과 mvc모델 적용에 중점을 두었습니다.

* 데모 : https://kkw10.github.io/

2019-07-22 06:38 UTC, nigayo commented
버그 : 
검색창에서 방향키를 쓰면 하이라이트 되는 영역이 매번 달라지는 거 같아요.

2019-07-22 07:05 UTC, crongro requested changes
수고하셨어요.
디렉토리구조가 좋고,  군더더기 없는 클래스구조를 만들었는데요.

표현방식에서 조금 개선하면 좋을 거 같아서 request changes 합니다.

2019-07-22 07:05 UTC, crongro commented on Javascript/Carousel/controllers/mainController.js
> +        let data = new Request('https://kkw10.github.io//Javascript/Carousel/models/localData.json')
URL은 개발서버, 운영서버에 따라서 자주 변경되는 부분이니까, 
init할때 인자로 받는게 더 좋겠죠.

2019-07-22 07:05 UTC, crongro commented on Javascript/Carousel/controllers/mainController.js
> +        this.arrows.arrowsEvent = this.mainEvent.bind(this);
bind사용법은 정확히 알고 계시길~

2019-07-22 07:05 UTC, crongro commented on Javascript/Carousel/controllers/mainController.js
>              this.cardNavi.init();
render -> init 

이런흐름으로 표현하고 있는데요.

render는 렌더링되는구나! 라고 생각되는데, 
init은 무엇을 하는거지? 라고 생각이 듭니다.

2019-07-22 07:05 UTC, crongro commented on Javascript/Carousel/controllers/mainController.js
>      mainEvent(event) {
낯선 이름입니다.
무엇을 하는지가 드러나지 않고있어요.

eventListener라면 listener나 handler라고 뒤에 붙여주는 것도 좋겠고요.

2019-07-22 07:05 UTC, crongro commented on Javascript/Carousel/views/arrowsView.js
>              this.arrowsEvent({detail : "@next"});
@ prefix 는 참신하네요.
 구별이 되는거 같아 전 괜찮아보입니다.

2019-07-22 07:05 UTC, crongro commented on Javascript/Carousel/views/arrowsView.js
> +        this.btnList.addEventListener('click', (evt) => {
destructuring을 활용해보세요.

여기 if문은 false상황에서  return 시키면 들여쓰기 없어질 듯.

2019-07-22 07:05 UTC, crongro commented on Javascript/Carousel/views/arrowsView.js
> +        let btnList = `
prevBtn, nextBtn 를 변수로 분리했는데, 굳이 그럴필요가 있을까? 고민되네요.
그냥 정적인 문자열들이라 하나의 html 문자열로 표현해도 괜찮을거 같은데요.

2019-07-22 07:05 UTC, nigayo commented on Javascript/Search/controllers/searchController.js
> +            let data = this.recentModel.data;
class의 속성을 직접접근하지  않고  getter/setter를 통해서 접근하는게 좋아요. 
명시적으로 표현되기도하고, 임의로 수정되는 것을 방지 하기 위함이기도 하죠. (속성은 감춰두는 겁니다.)

아니면 class에 getData() 라는 메서드를 만들어서 접근하세요.

2019-07-22 07:05 UTC, nigayo commented on Javascript/Search/models/recentModel.js
> +class RecentModel {
model을 통한 데이터 전달 시도가 좋습니다.

2019-07-22 07:05 UTC, nigayo commented on Javascript/Search/models/recentModel.js
> +        if(this.data.length > 5) {
5는 매직넘버~ 제거를 해주셔야..

2019-07-22 07:05 UTC, nigayo commented on Javascript/Search/views/autoList.js
> +        let node;
보통 초기화를 하는것도 좋죠
let node = ``;

그리고 아래에서는 filter나 reduce를 섞어서 쓰는등, forEach이외 방법을 적용해보세요.

2019-07-23 09:02 UTC, kkw10 commented
Koon 15-1 리뷰반영하여 수정완료했습니다. 리뷰부탁드립니다!

데모 : https://kkw10.github.io/

2019-07-30 05:59 UTC, crongro approved these changes
업데이트 된 내용을...알람이 안나와서 제가 놓쳤네요.
리뷰가 늦었습니다.

2019-07-30 05:59 UTC, nigayo commented on Javascript/Search/views/autoList.js
> +        let node = data
const를 잘 안쓰는데 먼저 쓰는게 좋아요.

2019-07-30 05:59 UTC, nigayo commented on Javascript/app.js
>  import SearchController from "./Search/controllers/searchController.js";
carouse 부분 import & 초기화
search 부분 import & 초기화

이 두개를 여기서 하니까, 복잡한데요. 
이걸 각각 하는 파일 2개를 만들어서 분리시키고, 여기서는 두 개를 호출해주는 식으로 단계를 하나더 만들어도 좋을 거 같군요.

2019-07-30 05:59 UTC, merged