[Q]: Step15-1
code-squad/javascript-amazon pull request #98
Opened 2019-07-22 17:49 UTC by park78951

미션 15-1 검토 부탁드립니다.

디버깅에서 굉장히 오래 시간을 소비한 것 같습니다... 디버깅을 하다보니 욕심이나서 더 고치고 수정하고, 하다보니 또 버그가 발견되고... 코드의 순서에 따른 버그 발생에 대한 관계를 이해하려다 보니 시간이 더 거렸던 것 같습니다. 최대한 리팩토링을 시도했지만 여전히 마음에 들지는 않습니다...  
지금은 html을 캐러셀과 나눴지만 다음 미션에서 합치도록 하겠습니다.

1. 기능 구현

• 검색어 입력 후 'Enter' 입력 또는 검색 아이콘 'Click'시 데이터 저장 후 창 종료
• 검색어 입력시 자동완성 창 생성
   • 해당 검색어가 들어간 단어에 대해 내림차순 정렬된 리스트 생성
   • 입력 후 300ms 이후 자동완성 창 생성
   • 해당 검색어에 해당하는 부분 굵은 글씨 표시
   • 최대 5개의 리스트 생성
• 앞서 저장된 데이터를 바탕으로 최근검색 리스트 생성
   • 가장 최근 검색된 검색어가 맨 위에 출력
   • 중복되는 검색어 입력시 가장 위에 오도록 설정
   • 최대 5개의 리스트 생성
• input 창 외에 클릭시 창의 Focus를 없애고 출력되었던 리스트 (최근검색 or 자동완성) 숨김
• 다시 input창 클릭시 리스트(최근검색 or 자동완성) 출력

2. 문제점 인식 및 의문점
• 초반 기능 구현에 초점을 맞추고 기능 구현 시 버그 수정을 하도록 초기 설계하였다가 디버깅에 너무 큰 어려움을 겪어 미리 예외처리 및 세밀한 설계가 필요함을 느꼈습니다만.. 초기 예외처리를 모두 파악하기가 어렵다면 추후 버그 발견시 최대한 쉽게 수정할 수 있는 방법으로 사전에 어떻게 작업을 해야할지 궁금합니다...
• 디자인 패턴을 최대한 사용하려다보니 검색창의 view는 필요성은 기능이 거의 없어 지워버렸고, 자동완성과 최근검색의 view 공통부분은 main view를 만들어 관리하였는데 호출시 main view에서 자동완성이나 최근검색의 메서드를 호출하면서 man view 클래스 자체의 메서드도 호출하다보니 코드가 굉장히 복잡해지고 어떤 방식이 옳은 것인지에 대해 궁금합니다...

3. 미구현 기능
• Fetch data - 자동완성을 위한 데이터들은 단순 무작위 단어 배열로 처리

2019-07-23 06:17 UTC, nigayo commented
몇차례 말씀드렸지만, 
'디자인 패턴을 최대한 사용하려다보니 ' 라는 부분이  전 틀렸다고 봅니다.
MVC등을 참고는 할 수 있지만 내 상황에 맞는 걸 만들려고 노력해보는 게 좋아요.

- 변경되는부분 분리하기
- 의존성을 낮게 유지하기

라는 점을 중요하게 생각하면서요.

2019-07-23 06:58 UTC, crongro requested changes
search/ 부분의 model/view/control 구분은 괜찮아보이는데요.

지금상태가  역할이 잘 나눠져 있으니, 이상태에서 버그를 모두 해결하는 것도 전 좋을거 같고요.
또는, 
단순화 시켜서 다시 구현하려면,  controller를 제거하는 것도 좋을 거 같아요. 그렇게 되면 view에서 model을 바로 구독하는 것이죠.

**어떤 방법으로 개선하던지 버그를 최소화 시켜서 만들어보세요!**

마지막으로, 전체적으로 디렉토리 구조가 복잡한데요. (carousel , promise등등) 
정리하면 좋겠네요.

2019-07-23 06:58 UTC, nigayo commented on src/js/search/model/searchModel.js
> +    this.autocomData = [
autocomData, 
이부분은 정적인데이터들이니까 모델이 있지 않고 config파일등으로 분리해두는 게 좋을 거 같네요.

2019-07-23 06:58 UTC, nigayo commented on src/js/search/view/AutocompleteView.js
> +    ut.appendElLastly(this.autocomplete, autocomList);
appendElLastly 함수이름이 잘 안읽히는거 같네요.

2019-07-24 15:39 UTC, park78951 commented on src/js/search/model/searchModel.js
> +    this.autocomData = [
model에서 검색 관련 데이터를 관리하는게 좋아보여서 넣었었는데 말씀하신대로
앞으로 정적인 데이터는 따로 관리하도록 하는게 좋을 것 같습니다.

2019-07-24 16:14 UTC, park78951 commented
피드백 감사합니다~ 
피드백 주신 점 반영해서 수정했습니다.

이번 미션에서 공통적인 역할을 Main View로 뺀 점이 굉장히 구좋를 복잡하게 만들지 않을까 생각했는데, 크롱이 말씀해주신 것과 다른 멤버 코드 보면서 단순하게 구현하기 위해 상속하도록 수정하고 controller도 없애보면서 어떤점이 불편한지, 더 나은지 판단해보면 좋을 것 같네요.

현재 Amazon Mission을 완료한 다음에 싹 다시 짜보도록 하겠습니다.

버그 있었던 점도 수정했습니다.
[데모](https://park78951.github.io/codesquad-Q/)

2019-07-30 06:02 UTC, crongro approved these changes
별 다른 수정없이 버그가 해결된거 같군요.
수정내용 확인했어요.
리뷰가 늦어서 미안합니다 흑

2019-07-30 06:02 UTC, merged